# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ-Z1.xdc

# Block Designs: bd/TT_OV/TT_OV.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_OV || ORIG_REF_NAME==TT_OV} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_processing_system7_0_0/TT_OV_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_OV_processing_system7_0_0 || ORIG_REF_NAME==TT_OV_processing_system7_0_0} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/TT_OV_TT_AXI_PERIPH_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_OV_TT_AXI_PERIPH_wrapper_0_0 || ORIG_REF_NAME==TT_OV_TT_AXI_PERIPH_wrapper_0_0} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_0/TT_AXI_PERIPH_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_0} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_xlconcat_0_0/TT_AXI_PERIPH_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_xlconcat_0_0 || ORIG_REF_NAME==TT_AXI_PERIPH_xlconcat_0_0} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_1/TT_AXI_PERIPH_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_1} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_xlconcat_1_0/TT_AXI_PERIPH_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_xlconcat_1_0 || ORIG_REF_NAME==TT_AXI_PERIPH_xlconcat_1_0} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_2/TT_AXI_PERIPH_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_2} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_xlslice_2_0/TT_AXI_PERIPH_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_xlslice_2_0 || ORIG_REF_NAME==TT_AXI_PERIPH_xlslice_2_0} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_xlslice_2_1/TT_AXI_PERIPH_xlslice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_xlslice_2_1 || ORIG_REF_NAME==TT_AXI_PERIPH_xlslice_2_1} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_LSB_T1_1/TT_AXI_PERIPH_LSB_T1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_LSB_T1_1 || ORIG_REF_NAME==TT_AXI_PERIPH_LSB_T1_1} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_MSB_T1_1/TT_AXI_PERIPH_MSB_T1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_MSB_T1_1 || ORIG_REF_NAME==TT_AXI_PERIPH_MSB_T1_1} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_2/TT_AXI_PERIPH_T1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_2 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_2} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_LSB_T1_2/TT_AXI_PERIPH_LSB_T1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_LSB_T1_2 || ORIG_REF_NAME==TT_AXI_PERIPH_LSB_T1_2} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_MSB_T1_2/TT_AXI_PERIPH_MSB_T1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_MSB_T1_2 || ORIG_REF_NAME==TT_AXI_PERIPH_MSB_T1_2} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_3/TT_AXI_PERIPH_T1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_3 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_3} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_LSB_T1_3/TT_AXI_PERIPH_LSB_T1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_LSB_T1_3 || ORIG_REF_NAME==TT_AXI_PERIPH_LSB_T1_3} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_MSB_T1_3/TT_AXI_PERIPH_MSB_T1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_MSB_T1_3 || ORIG_REF_NAME==TT_AXI_PERIPH_MSB_T1_3} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_4/TT_AXI_PERIPH_T1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_4 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_4} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_TIME_TAG_M_0_0/TT_AXI_PERIPH_TIME_TAG_M_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_TIME_TAG_M_0_0 || ORIG_REF_NAME==TT_AXI_PERIPH_TIME_TAG_M_0_0} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_TIME_TAG_M_0_0/src/TT_ctr/TT_ctr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_ctr || ORIG_REF_NAME==TT_ctr} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_xbar_0/TT_OV_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_OV_xbar_0 || ORIG_REF_NAME==TT_OV_xbar_0} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_ps7_0_axi_periph_0/TT_OV_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_OV_ps7_0_axi_periph_0 || ORIG_REF_NAME==TT_OV_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_rst_ps7_0_100M_0/TT_OV_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==TT_OV_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_clk_wiz_0_1/TT_OV_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_OV_clk_wiz_0_1 || ORIG_REF_NAME==TT_OV_clk_wiz_0_1} -quiet] -quiet

# IP: bd/TT_OV/ip/TT_OV_auto_pc_0/TT_OV_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_OV_auto_pc_0 || ORIG_REF_NAME==TT_OV_auto_pc_0} -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_processing_system7_0_0/TT_OV_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_OV_processing_system7_0_0 || ORIG_REF_NAME==TT_OV_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_ooc.xdc

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_0/TT_AXI_PERIPH_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_0/TT_AXI_PERIPH_axi_gpio_0_0_ooc.xdc

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_0/TT_AXI_PERIPH_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_1/TT_AXI_PERIPH_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_1/TT_AXI_PERIPH_axi_gpio_0_1_ooc.xdc

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_1/TT_AXI_PERIPH_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_2/TT_AXI_PERIPH_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_2/TT_AXI_PERIPH_axi_gpio_0_2_ooc.xdc

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_2/TT_AXI_PERIPH_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_2/TT_AXI_PERIPH_T1_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_2 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_2/TT_AXI_PERIPH_T1_2_ooc.xdc

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_2/TT_AXI_PERIPH_T1_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_2 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_3/TT_AXI_PERIPH_T1_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_3 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_3/TT_AXI_PERIPH_T1_3_ooc.xdc

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_3/TT_AXI_PERIPH_T1_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_3 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_4/TT_AXI_PERIPH_T1_4_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_4 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_4/TT_AXI_PERIPH_T1_4_ooc.xdc

# XDC: bd/TT_OV/ip/TT_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_4/TT_AXI_PERIPH_T1_4.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_4 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_rst_ps7_0_100M_0/TT_OV_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==TT_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_rst_ps7_0_100M_0/TT_OV_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==TT_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_clk_wiz_0_1/TT_OV_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_OV_clk_wiz_0_1 || ORIG_REF_NAME==TT_OV_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_clk_wiz_0_1/TT_OV_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_OV_clk_wiz_0_1 || ORIG_REF_NAME==TT_OV_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/TT_OV/ip/TT_OV_clk_wiz_0_1/TT_OV_clk_wiz_0_1_ooc.xdc

# XDC: bd/TT_OV/ip/TT_OV_auto_pc_0/TT_OV_auto_pc_0_ooc.xdc

# XDC: bd/TT_OV/TT_OV_ooc.xdc
