set_property PACKAGE_PIN L15 [get_ports TT_WAITING]
set_property PACKAGE_PIN G14 [get_ports TT_LISTENING]
set_property IOSTANDARD LVCMOS33 [get_ports TT_LISTENING]
set_property IOSTANDARD LVCMOS33 [get_ports TT_WAITING]
set_property PACKAGE_PIN G17 [get_ports ST_ARMED]
set_property PACKAGE_PIN L14 [get_ports ST_WAITING]
set_property IOSTANDARD LVCMOS33 [get_ports ST_ARMED]
set_property IOSTANDARD LVCMOS33 [get_ports ST_WAITING]
set_property PACKAGE_PIN N15 [get_ports CT_ARMED]
set_property PACKAGE_PIN M15 [get_ports CT_WAITING]
set_property IOSTANDARD LVCMOS33 [get_ports CT_ARMED]
set_property IOSTANDARD LVCMOS33 [get_ports CT_WAITING]
set_property IOSTANDARD LVCMOS33 [get_ports {SIG_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SIG_OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SIG_OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SIG_OUT[0]}]
set_property PACKAGE_PIN V16 [get_ports {SIG_OUT[0]}]
set_property PACKAGE_PIN W16 [get_ports {SIG_OUT[1]}]
set_property PACKAGE_PIN V12 [get_ports {SIG_OUT[2]}]
set_property PACKAGE_PIN W13 [get_ports {SIG_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DEBUG[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DEBUG[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DEBUG[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DEBUG[0]}]
set_property PACKAGE_PIN R14 [get_ports {DEBUG[0]}]
set_property PACKAGE_PIN P14 [get_ports {DEBUG[1]}]
set_property PACKAGE_PIN N16 [get_ports {DEBUG[2]}]
set_property PACKAGE_PIN M14 [get_ports {DEBUG[3]}]
set_property PACKAGE_PIN W14 [get_ports CH0]
set_property PACKAGE_PIN Y14 [get_ports CH1]
set_property PACKAGE_PIN T11 [get_ports CH2]
set_property PACKAGE_PIN T10 [get_ports CH3]
set_property IOSTANDARD LVCMOS33 [get_ports CH0]
set_property IOSTANDARD LVCMOS33 [get_ports CH1]
set_property IOSTANDARD LVCMOS33 [get_ports CH2]
set_property IOSTANDARD LVCMOS33 [get_ports CH3]
set_property PACKAGE_PIN Y19 [get_ports E_TRIG]
set_property IOSTANDARD LVCMOS33 [get_ports E_TRIG]
set_property PACKAGE_PIN Y18 [get_ports TRIG_T0]
set_property IOSTANDARD LVCMOS33 [get_ports TRIG_T0]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]

create_pblock pblock_SDDR_ST_0
add_cells_to_pblock [get_pblocks pblock_SDDR_ST_0] [get_cells -quiet [list SP_OV_i/SDDR_AXI_ST_wrapper_0/U0/SDDR_AXI_ST_i/SDDR_ST_0]]
resize_pblock [get_pblocks pblock_SDDR_ST_0] -add {SLICE_X80Y75:SLICE_X89Y79}
create_pblock pblock_SDDR_CT_0
add_cells_to_pblock [get_pblocks pblock_SDDR_CT_0] [get_cells -quiet [list SP_OV_i/SDDR_CT_AXI_wrapper_0/U0/SDDR_CT_AXI_i/SDDR_CT_0]]
resize_pblock [get_pblocks pblock_SDDR_CT_0] -add {SLICE_X80Y80:SLICE_X89Y87}
create_pblock pblock_SDDR_TT_0
add_cells_to_pblock [get_pblocks pblock_SDDR_TT_0] [get_cells -quiet [list SP_OV_i/SDDR_TT_AXI_wrapper_0/U0/SDDR_TT_AXI_i/SDDR_TT_0]]
resize_pblock [get_pblocks pblock_SDDR_TT_0] -add {SLICE_X80Y88:SLICE_X89Y99}
