# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ_Z1_X.xdc

# Block Designs: bd/Counter_Overlay/Counter_Overlay.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay || ORIG_REF_NAME==Counter_Overlay} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_processing_system7_0_0/Counter_Overlay_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_processing_system7_0_0 || ORIG_REF_NAME==Counter_Overlay_processing_system7_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_ps7_0_axi_periph_0/Counter_Overlay_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_ps7_0_axi_periph_0 || ORIG_REF_NAME==Counter_Overlay_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_rst_ps7_0_100M_0/Counter_Overlay_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_rst_ps7_0_100M_0 || ORIG_REF_NAME==Counter_Overlay_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_clk_wiz_0_0/Counter_Overlay_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_clk_wiz_0_0 || ORIG_REF_NAME==Counter_Overlay_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_clk_wiz_1_0/Counter_Overlay_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_clk_wiz_1_0 || ORIG_REF_NAME==Counter_Overlay_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_xbar_0/Counter_Overlay_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_xbar_0 || ORIG_REF_NAME==Counter_Overlay_xbar_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_COUNTER_wrapper_0_0/Counter_Overlay_COUNTER_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_COUNTER_wrapper_0_0 || ORIG_REF_NAME==Counter_Overlay_COUNTER_wrapper_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_COUNTER_wrapper_0_0/src/COUNTER_xlconstant_0_0/COUNTER_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_xlconstant_0_0 || ORIG_REF_NAME==COUNTER_xlconstant_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_COUNTER_wrapper_0_0/src/COUNTER_xlslice_0_0/COUNTER_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_xlslice_0_0 || ORIG_REF_NAME==COUNTER_xlslice_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_COUNTER_wrapper_0_0/src/COUNTER_xlslice_1_0/COUNTER_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_xlslice_1_0 || ORIG_REF_NAME==COUNTER_xlslice_1_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_0_0/Counter_Overlay_CH_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_CH_0_0 || ORIG_REF_NAME==Counter_Overlay_CH_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_0_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_0_0/src/COUNTER_xlconstant_0_0/COUNTER_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_xlconstant_0_0 || ORIG_REF_NAME==COUNTER_xlconstant_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_0_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_0_0/src/COUNTER_xlslice_0_0/COUNTER_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_xlslice_0_0 || ORIG_REF_NAME==COUNTER_xlslice_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_0_0/src/COUNTER_xlslice_1_0/COUNTER_xlslice_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_xlslice_1_0 || ORIG_REF_NAME==COUNTER_xlslice_1_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_1_0/Counter_Overlay_CH_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_CH_1_0 || ORIG_REF_NAME==Counter_Overlay_CH_1_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_1_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_1_0/src/COUNTER_xlconstant_0_0/COUNTER_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_xlconstant_0_0 || ORIG_REF_NAME==COUNTER_xlconstant_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_1_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_1_0/src/COUNTER_xlslice_0_0/COUNTER_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_xlslice_0_0 || ORIG_REF_NAME==COUNTER_xlslice_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_1_0/src/COUNTER_xlslice_1_0/COUNTER_xlslice_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_xlslice_1_0 || ORIG_REF_NAME==COUNTER_xlslice_1_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_2_0/Counter_Overlay_CH_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_CH_2_0 || ORIG_REF_NAME==Counter_Overlay_CH_2_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_2_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_2_0/src/COUNTER_xlconstant_0_0/COUNTER_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_xlconstant_0_0 || ORIG_REF_NAME==COUNTER_xlconstant_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_2_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_2_0/src/COUNTER_xlslice_0_0/COUNTER_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_xlslice_0_0 || ORIG_REF_NAME==COUNTER_xlslice_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_CH_2_0/src/COUNTER_xlslice_1_0/COUNTER_xlslice_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_xlslice_1_0 || ORIG_REF_NAME==COUNTER_xlslice_1_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_xlslice_0_0/Counter_Overlay_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_xlslice_0_0 || ORIG_REF_NAME==Counter_Overlay_xlslice_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_channel_sl_0_0/Counter_Overlay_channel_sl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_channel_sl_0_0 || ORIG_REF_NAME==Counter_Overlay_channel_sl_0_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_channel_sl_1_0/Counter_Overlay_channel_sl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_channel_sl_1_0 || ORIG_REF_NAME==Counter_Overlay_channel_sl_1_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_channel_sl_2_0/Counter_Overlay_channel_sl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_channel_sl_2_0 || ORIG_REF_NAME==Counter_Overlay_channel_sl_2_0} -quiet] -quiet

# IP: bd/Counter_Overlay/ip/Counter_Overlay_auto_pc_0/Counter_Overlay_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_Overlay_auto_pc_0 || ORIG_REF_NAME==Counter_Overlay_auto_pc_0} -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_processing_system7_0_0/Counter_Overlay_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Counter_Overlay_processing_system7_0_0 || ORIG_REF_NAME==Counter_Overlay_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_rst_ps7_0_100M_0/Counter_Overlay_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Counter_Overlay_rst_ps7_0_100M_0 || ORIG_REF_NAME==Counter_Overlay_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_rst_ps7_0_100M_0/Counter_Overlay_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Counter_Overlay_rst_ps7_0_100M_0 || ORIG_REF_NAME==Counter_Overlay_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_clk_wiz_0_0/Counter_Overlay_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Counter_Overlay_clk_wiz_0_0 || ORIG_REF_NAME==Counter_Overlay_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_clk_wiz_0_0/Counter_Overlay_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Counter_Overlay_clk_wiz_0_0 || ORIG_REF_NAME==Counter_Overlay_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_clk_wiz_0_0/Counter_Overlay_clk_wiz_0_0_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_clk_wiz_1_0/Counter_Overlay_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Counter_Overlay_clk_wiz_1_0 || ORIG_REF_NAME==Counter_Overlay_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_clk_wiz_1_0/Counter_Overlay_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Counter_Overlay_clk_wiz_1_0 || ORIG_REF_NAME==Counter_Overlay_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_clk_wiz_1_0/Counter_Overlay_clk_wiz_1_0_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_xbar_0/Counter_Overlay_xbar_0_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_COUNTER_wrapper_0_0/src/COUNTER_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_0_0/src/COUNTER_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_0_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_0_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_0_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_0_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_0_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_0_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_1_0/src/COUNTER_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_1_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_1_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_1_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_1_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_1_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_1_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_2_0/src/COUNTER_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_2_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_2_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_2_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_2_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_2_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_ooc.xdc

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_CH_2_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Counter_Overlay/ip/Counter_Overlay_auto_pc_0/Counter_Overlay_auto_pc_0_ooc.xdc

# XDC: bd/Counter_Overlay/Counter_Overlay_ooc.xdc
