set_property IOSTANDARD LVCMOS33 [get_ports CH0]
set_property IOSTANDARD LVCMOS33 [get_ports CH1]
set_property PACKAGE_PIN W14 [get_ports CH0]
set_property PACKAGE_PIN Y14 [get_ports CH1]
set_property PULLDOWN true [get_ports CH0]
set_property PULLDOWN true [get_ports CH1]
