# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ-Z1.xdc

# Block Designs: bd/PG_OV/PG_OV.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_OV || ORIG_REF_NAME==PG_OV} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_processing_system7_0_0/PG_OV_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_OV_processing_system7_0_0 || ORIG_REF_NAME==PG_OV_processing_system7_0_0} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_ps7_0_axi_periph_0/PG_OV_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_OV_ps7_0_axi_periph_0 || ORIG_REF_NAME==PG_OV_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_rst_ps7_0_100M_0/PG_OV_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==PG_OV_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_clk_wiz_0_0/PG_OV_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_OV_clk_wiz_0_0 || ORIG_REF_NAME==PG_OV_clk_wiz_0_0} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_xbar_0/PG_OV_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_OV_xbar_0 || ORIG_REF_NAME==PG_OV_xbar_0} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/PG_OV_PG_AXI_CH_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_OV_PG_AXI_CH_wrapper_0_0 || ORIG_REF_NAME==PG_OV_PG_AXI_CH_wrapper_0_0} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/c_counter_binary_0/c_counter_binary_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_0 || ORIG_REF_NAME==c_counter_binary_0} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_GEN_CORE_4_0/PG_AXI_CH_GEN_CORE_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_CH_GEN_CORE_4_0 || ORIG_REF_NAME==PG_AXI_CH_GEN_CORE_4_0} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_GEN_CORE_4_0/src/C_COUNTER_INT/C_COUNTER_INT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==C_COUNTER_INT || ORIG_REF_NAME==C_COUNTER_INT} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_GEN_CORE_0_1/PG_AXI_CH_GEN_CORE_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_CH_GEN_CORE_0_1 || ORIG_REF_NAME==PG_AXI_CH_GEN_CORE_0_1} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_GEN_CORE_0_1/src/C_COUNTER_INT/C_COUNTER_INT.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==C_COUNTER_INT || ORIG_REF_NAME==C_COUNTER_INT} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_GEN_CORE_1_1/PG_AXI_CH_GEN_CORE_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_CH_GEN_CORE_1_1 || ORIG_REF_NAME==PG_AXI_CH_GEN_CORE_1_1} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_GEN_CORE_1_1/src/C_COUNTER_INT/C_COUNTER_INT.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==C_COUNTER_INT || ORIG_REF_NAME==C_COUNTER_INT} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_GEN_CORE_2_1/PG_AXI_CH_GEN_CORE_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_CH_GEN_CORE_2_1 || ORIG_REF_NAME==PG_AXI_CH_GEN_CORE_2_1} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_GEN_CORE_2_1/src/C_COUNTER_INT/C_COUNTER_INT.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==C_COUNTER_INT || ORIG_REF_NAME==C_COUNTER_INT} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_0_2/PG_AXI_CH_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_0_2 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_0_2} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_ch0_0/PG_AXI_CH_axi_gpio_ch0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_ch0_0 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_ch0_0} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_ch1_0/PG_AXI_CH_axi_gpio_ch1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_ch1_0 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_ch1_0} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_ch2_0/PG_AXI_CH_axi_gpio_ch2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_ch2_0 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_ch2_0} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_0_4/PG_AXI_CH_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_0_4 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_0_4} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_delay_0_0/PG_AXI_CH_axi_delay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_delay_0_0 || ORIG_REF_NAME==PG_AXI_CH_axi_delay_0_0} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_0_5/PG_AXI_CH_axi_gpio_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_0_5 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_0_5} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_axi_gpio_0_0/PG_OV_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_OV_axi_gpio_0_0 || ORIG_REF_NAME==PG_OV_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PG_OV/ip/PG_OV_auto_pc_0/PG_OV_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_OV_auto_pc_0 || ORIG_REF_NAME==PG_OV_auto_pc_0} -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_processing_system7_0_0/PG_OV_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_OV_processing_system7_0_0 || ORIG_REF_NAME==PG_OV_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_rst_ps7_0_100M_0/PG_OV_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==PG_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_rst_ps7_0_100M_0/PG_OV_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==PG_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_clk_wiz_0_0/PG_OV_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_OV_clk_wiz_0_0 || ORIG_REF_NAME==PG_OV_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_clk_wiz_0_0/PG_OV_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_OV_clk_wiz_0_0 || ORIG_REF_NAME==PG_OV_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_clk_wiz_0_0/PG_OV_clk_wiz_0_0_ooc.xdc

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_ooc.xdc

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_0_2/PG_AXI_CH_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_0_2 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_0_2/PG_AXI_CH_axi_gpio_0_2_ooc.xdc

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_0_2/PG_AXI_CH_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_0_2 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_ch0_0/PG_AXI_CH_axi_gpio_ch0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_ch0_0 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_ch0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_ch0_0/PG_AXI_CH_axi_gpio_ch0_0_ooc.xdc

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_ch0_0/PG_AXI_CH_axi_gpio_ch0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_ch0_0 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_ch0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_ch1_0/PG_AXI_CH_axi_gpio_ch1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_ch1_0 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_ch1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_ch1_0/PG_AXI_CH_axi_gpio_ch1_0_ooc.xdc

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_ch1_0/PG_AXI_CH_axi_gpio_ch1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_ch1_0 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_ch1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_ch2_0/PG_AXI_CH_axi_gpio_ch2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_ch2_0 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_ch2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_ch2_0/PG_AXI_CH_axi_gpio_ch2_0_ooc.xdc

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_ch2_0/PG_AXI_CH_axi_gpio_ch2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_ch2_0 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_ch2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_0_4/PG_AXI_CH_axi_gpio_0_4_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_0_4 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_0_4/PG_AXI_CH_axi_gpio_0_4_ooc.xdc

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_0_4/PG_AXI_CH_axi_gpio_0_4.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_0_4 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_delay_0_0/PG_AXI_CH_axi_delay_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_delay_0_0 || ORIG_REF_NAME==PG_AXI_CH_axi_delay_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_delay_0_0/PG_AXI_CH_axi_delay_0_0_ooc.xdc

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_delay_0_0/PG_AXI_CH_axi_delay_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_delay_0_0 || ORIG_REF_NAME==PG_AXI_CH_axi_delay_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_0_5/PG_AXI_CH_axi_gpio_0_5_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_0_5 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_0_5} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_0_5/PG_AXI_CH_axi_gpio_0_5_ooc.xdc

# XDC: bd/PG_OV/ip/PG_OV_PG_AXI_CH_wrapper_0_0/src/PG_AXI_CH_axi_gpio_0_5/PG_AXI_CH_axi_gpio_0_5.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_CH_axi_gpio_0_5 || ORIG_REF_NAME==PG_AXI_CH_axi_gpio_0_5} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_axi_gpio_0_0/PG_OV_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_OV_axi_gpio_0_0 || ORIG_REF_NAME==PG_OV_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_axi_gpio_0_0/PG_OV_axi_gpio_0_0_ooc.xdc

# XDC: bd/PG_OV/ip/PG_OV_axi_gpio_0_0/PG_OV_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_OV_axi_gpio_0_0 || ORIG_REF_NAME==PG_OV_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PG_OV/ip/PG_OV_auto_pc_0/PG_OV_auto_pc_0_ooc.xdc

# XDC: bd/PG_OV/PG_OV_ooc.xdc
