# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ-Z1.xdc

# Block Designs: bd/SP_OV/SP_OV.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV || ORIG_REF_NAME==SP_OV} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_processing_system7_0_0/SP_OV_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_processing_system7_0_0 || ORIG_REF_NAME==SP_OV_processing_system7_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_rst_ps7_0_100M_0/SP_OV_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==SP_OV_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/SP_OV_P_COUNTER_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_P_COUNTER_wrapper_0_0 || ORIG_REF_NAME==SP_OV_P_COUNTER_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/PC_T_CTR/PC_T_CTR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PC_T_CTR || ORIG_REF_NAME==PC_T_CTR} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data_0/P_COUNTER_axi_gpio_data_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data1_0/P_COUNTER_axi_gpio_data1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data2_0/P_COUNTER_axi_gpio_data2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data3_0/P_COUNTER_axi_gpio_data3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util_0/P_COUNTER_axi_gpio_util_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util1_0/P_COUNTER_axi_gpio_util1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util2_0/P_COUNTER_axi_gpio_util2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util3_0/P_COUNTER_axi_gpio_util3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_c_counter_binary_0_0/P_COUNTER_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_c_counter_binary_0_0 || ORIG_REF_NAME==P_COUNTER_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_c_counter_binary_1_0/P_COUNTER_c_counter_binary_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_c_counter_binary_1_0 || ORIG_REF_NAME==P_COUNTER_c_counter_binary_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_c_counter_binary_2_0/P_COUNTER_c_counter_binary_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_c_counter_binary_2_0 || ORIG_REF_NAME==P_COUNTER_c_counter_binary_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_c_counter_binary_3_0/P_COUNTER_c_counter_binary_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_c_counter_binary_3_0 || ORIG_REF_NAME==P_COUNTER_c_counter_binary_3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_0_0/P_COUNTER_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_0_0 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_1_0/P_COUNTER_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_1_0 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_2_0/P_COUNTER_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_2_0 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_3_0/P_COUNTER_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_3_0 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_4_0/P_COUNTER_util_vector_logic_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_4_0 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_4_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_4_1/P_COUNTER_util_vector_logic_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_4_1 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_4_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_ex_trig_or_1_0/P_COUNTER_ex_trig_or_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_ex_trig_or_1_0 || ORIG_REF_NAME==P_COUNTER_ex_trig_or_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_ex_trig_or_2_0/P_COUNTER_ex_trig_or_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_ex_trig_or_2_0 || ORIG_REF_NAME==P_COUNTER_ex_trig_or_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_4_2/P_COUNTER_util_vector_logic_4_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_4_2 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_4_2} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_ex_stop_or_0_0/P_COUNTER_ex_stop_or_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_ex_stop_or_0_0 || ORIG_REF_NAME==P_COUNTER_ex_stop_or_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_ex_stop_or_1_0/P_COUNTER_ex_stop_or_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_ex_stop_or_1_0 || ORIG_REF_NAME==P_COUNTER_ex_stop_or_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_ex_stop_or_2_0/P_COUNTER_ex_stop_or_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_ex_stop_or_2_0 || ORIG_REF_NAME==P_COUNTER_ex_stop_or_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/SP_OV_DDS_AXI_PERIPH_wrapp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_DDS_AXI_PERIPH_wrapp_0_0 || ORIG_REF_NAME==SP_OV_DDS_AXI_PERIPH_wrapp_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_DDS_COM_wrapper_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_DDS_COM_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_DEL_CTR/DDS_DEL_CTR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_DEL_CTR || ORIG_REF_NAME==DDS_DEL_CTR} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_COM_dds_compiler_0_0/DDS_COM_dds_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_dds_compiler_0_0 || ORIG_REF_NAME==DDS_COM_dds_compiler_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_COM_dds_compiler_0_1/DDS_COM_dds_compiler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_dds_compiler_0_1 || ORIG_REF_NAME==DDS_COM_dds_compiler_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_COM_dds_compiler_1_0/DDS_COM_dds_compiler_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_dds_compiler_1_0 || ORIG_REF_NAME==DDS_COM_dds_compiler_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_COM_dds_compiler_2_0/DDS_COM_dds_compiler_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_dds_compiler_2_0 || ORIG_REF_NAME==DDS_COM_dds_compiler_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_COM_xlconcat_0_0/DDS_COM_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_xlconcat_0_0 || ORIG_REF_NAME==DDS_COM_xlconcat_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_COM_xlconcat_0_1/DDS_COM_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_xlconcat_0_1 || ORIG_REF_NAME==DDS_COM_xlconcat_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_0/DDS_AXI_PERIPH_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_0_0/DDS_AXI_PERIPH_phase_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_1_0/DDS_AXI_PERIPH_phase_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_1_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_2_0/DDS_AXI_PERIPH_phase_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_2_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlconcat_0_0/DDS_AXI_PERIPH_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlconcat_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlconcat_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlconcat_0_1/DDS_AXI_PERIPH_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlconcat_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlconcat_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlconcat_1_0/DDS_AXI_PERIPH_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlconcat_1_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlconcat_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlconcat_2_0/DDS_AXI_PERIPH_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlconcat_2_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlconcat_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_1/DDS_AXI_PERIPH_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_0_1/DDS_AXI_PERIPH_aux_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_1_1/DDS_AXI_PERIPH_aux_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_1_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_1_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_2_1/DDS_AXI_PERIPH_aux_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_2_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_2_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_2/DDS_AXI_PERIPH_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_2} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlslice_0_0/DDS_AXI_PERIPH_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlslice_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlslice_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlslice_0_1/DDS_AXI_PERIPH_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlslice_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlslice_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlslice_1_0/DDS_AXI_PERIPH_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlslice_1_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlslice_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlslice_2_0/DDS_AXI_PERIPH_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlslice_2_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlslice_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlconcat_4_0/DDS_AXI_PERIPH_xlconcat_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlconcat_4_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlconcat_4_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_ENABLER_0_0/SP_OV_ENABLER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_ENABLER_0_0 || ORIG_REF_NAME==SP_OV_ENABLER_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_axi_gpio_0_0/SP_OV_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_axi_gpio_0_0 || ORIG_REF_NAME==SP_OV_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_xlslice_0_0/SP_OV_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_xlslice_0_0 || ORIG_REF_NAME==SP_OV_xlslice_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_xlslice_0_1/SP_OV_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_xlslice_0_1 || ORIG_REF_NAME==SP_OV_xlslice_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_axi_gpio_0_1/SP_OV_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_axi_gpio_0_1 || ORIG_REF_NAME==SP_OV_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_clk_wiz_0_1/SP_OV_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_0_1 || ORIG_REF_NAME==SP_OV_clk_wiz_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_clk_wiz_1_1/SP_OV_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_1_1 || ORIG_REF_NAME==SP_OV_clk_wiz_1_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/SP_OV_SDDR_AXI_ST_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_SDDR_AXI_ST_wrapper_0_0 || ORIG_REF_NAME==SP_OV_SDDR_AXI_ST_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_SDDR_ST_0_0/SDDR_AXI_ST_SDDR_ST_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_SDDR_ST_0_0 || ORIG_REF_NAME==SDDR_AXI_ST_SDDR_ST_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_SDDR_ST_0_0/src/ST_TIMER/ST_TIMER.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TIMER || ORIG_REF_NAME==ST_TIMER} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_axi_gpio_0_0/SDDR_AXI_ST_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_axi_gpio_0_0 || ORIG_REF_NAME==SDDR_AXI_ST_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_axi_gpio_0_1/SDDR_AXI_ST_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_axi_gpio_0_1 || ORIG_REF_NAME==SDDR_AXI_ST_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_util_vector_logic_0_0/SDDR_AXI_ST_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_util_vector_logic_0_0 || ORIG_REF_NAME==SDDR_AXI_ST_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_util_vector_logic_1_0/SDDR_AXI_ST_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_util_vector_logic_1_0 || ORIG_REF_NAME==SDDR_AXI_ST_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_fifo_generator_0_0/SDDR_AXI_ST_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_fifo_generator_0_0 || ORIG_REF_NAME==SDDR_AXI_ST_fifo_generator_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_util_vector_logic_2_0/SDDR_AXI_ST_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_util_vector_logic_2_0 || ORIG_REF_NAME==SDDR_AXI_ST_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_xlslice_0_0/SDDR_AXI_ST_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_xlslice_0_0 || ORIG_REF_NAME==SDDR_AXI_ST_xlslice_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_xlslice_0_1/SDDR_AXI_ST_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_xlslice_0_1 || ORIG_REF_NAME==SDDR_AXI_ST_xlslice_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_xlslice_1_0/SDDR_AXI_ST_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_xlslice_1_0 || ORIG_REF_NAME==SDDR_AXI_ST_xlslice_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_xlconcat_0_1/SDDR_AXI_ST_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_xlconcat_0_1 || ORIG_REF_NAME==SDDR_AXI_ST_xlconcat_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_xlconcat_1_0/SDDR_AXI_ST_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_xlconcat_1_0 || ORIG_REF_NAME==SDDR_AXI_ST_xlconcat_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_util_vector_logic_3_0/SDDR_AXI_ST_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_util_vector_logic_3_0 || ORIG_REF_NAME==SDDR_AXI_ST_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/SP_OV_SDDR_CT_AXI_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_SDDR_CT_AXI_wrapper_0_0 || ORIG_REF_NAME==SP_OV_SDDR_CT_AXI_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_SDDR_CT_0_0/SDDR_CT_AXI_SDDR_CT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_SDDR_CT_0_0 || ORIG_REF_NAME==SDDR_CT_AXI_SDDR_CT_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_SDDR_CT_0_0/src/CT_TIMER/CT_TIMER.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CT_TIMER || ORIG_REF_NAME==CT_TIMER} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_axi_gpio_0_0/SDDR_CT_AXI_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_axi_gpio_0_0 || ORIG_REF_NAME==SDDR_CT_AXI_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_axi_gpio_0_1/SDDR_CT_AXI_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_axi_gpio_0_1 || ORIG_REF_NAME==SDDR_CT_AXI_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_fifo_generator_0_0/SDDR_CT_AXI_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_fifo_generator_0_0 || ORIG_REF_NAME==SDDR_CT_AXI_fifo_generator_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_xlconcat_0_1/SDDR_CT_AXI_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_xlconcat_0_1 || ORIG_REF_NAME==SDDR_CT_AXI_xlconcat_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_util_vector_logic_0_0/SDDR_CT_AXI_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_util_vector_logic_0_0 || ORIG_REF_NAME==SDDR_CT_AXI_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_util_vector_logic_0_1/SDDR_CT_AXI_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_util_vector_logic_0_1 || ORIG_REF_NAME==SDDR_CT_AXI_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_util_vector_logic_2_0/SDDR_CT_AXI_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_util_vector_logic_2_0 || ORIG_REF_NAME==SDDR_CT_AXI_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_util_vector_logic_3_0/SDDR_CT_AXI_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_util_vector_logic_3_0 || ORIG_REF_NAME==SDDR_CT_AXI_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_xlconcat_1_1/SDDR_CT_AXI_xlconcat_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_xlconcat_1_1 || ORIG_REF_NAME==SDDR_CT_AXI_xlconcat_1_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_xlslice_0_0/SDDR_CT_AXI_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_xlslice_0_0 || ORIG_REF_NAME==SDDR_CT_AXI_xlslice_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_xlslice_0_1/SDDR_CT_AXI_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_xlslice_0_1 || ORIG_REF_NAME==SDDR_CT_AXI_xlslice_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/SP_OV_SDDR_TT_AXI_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_SDDR_TT_AXI_wrapper_0_0 || ORIG_REF_NAME==SP_OV_SDDR_TT_AXI_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_SDDR_TT_0_0/SDDR_TT_AXI_SDDR_TT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_SDDR_TT_0_0 || ORIG_REF_NAME==SDDR_TT_AXI_SDDR_TT_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_SDDR_TT_0_0/src/sddrtt_timer/sddrtt_timer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sddrtt_timer || ORIG_REF_NAME==sddrtt_timer} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_0/SDDR_TT_AXI_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_axi_gpio_0_0 || ORIG_REF_NAME==SDDR_TT_AXI_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_DATA0_0/SDDR_TT_AXI_DATA0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_DATA0_0 || ORIG_REF_NAME==SDDR_TT_AXI_DATA0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_1/SDDR_TT_AXI_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_axi_gpio_0_1 || ORIG_REF_NAME==SDDR_TT_AXI_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_2/SDDR_TT_AXI_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_axi_gpio_0_2 || ORIG_REF_NAME==SDDR_TT_AXI_axi_gpio_0_2} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_3/SDDR_TT_AXI_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_axi_gpio_0_3 || ORIG_REF_NAME==SDDR_TT_AXI_axi_gpio_0_3} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_fifo_generator_0_0/SDDR_TT_AXI_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_fifo_generator_0_0 || ORIG_REF_NAME==SDDR_TT_AXI_fifo_generator_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_xlconcat_1_0/SDDR_TT_AXI_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_xlconcat_1_0 || ORIG_REF_NAME==SDDR_TT_AXI_xlconcat_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_util_vector_logic_0_0/SDDR_TT_AXI_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_util_vector_logic_0_0 || ORIG_REF_NAME==SDDR_TT_AXI_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_xlslice_0_0/SDDR_TT_AXI_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_xlslice_0_0 || ORIG_REF_NAME==SDDR_TT_AXI_xlslice_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_xlslice_0_1/SDDR_TT_AXI_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_xlslice_0_1 || ORIG_REF_NAME==SDDR_TT_AXI_xlslice_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_xlslice_1_0/SDDR_TT_AXI_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_xlslice_1_0 || ORIG_REF_NAME==SDDR_TT_AXI_xlslice_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_xlconcat_0_1/SDDR_TT_AXI_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_xlconcat_0_1 || ORIG_REF_NAME==SDDR_TT_AXI_xlconcat_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_clk_wiz_0_2/SP_OV_clk_wiz_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_0_2 || ORIG_REF_NAME==SP_OV_clk_wiz_0_2} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DESERIALIZER_B_wrapp_0_0/SP_OV_DESERIALIZER_B_wrapp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_DESERIALIZER_B_wrapp_0_0 || ORIG_REF_NAME==SP_OV_DESERIALIZER_B_wrapp_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DESERIALIZER_B_wrapp_0_0/src/DESERIALIZER_B_util_vector_logic_0_0/DESERIALIZER_B_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DESERIALIZER_B_util_vector_logic_0_0 || ORIG_REF_NAME==DESERIALIZER_B_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DESERIALIZER_B_wrapp_0_0/src/DESERIALIZER_B_axi_gpio_0_0/DESERIALIZER_B_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DESERIALIZER_B_axi_gpio_0_0 || ORIG_REF_NAME==DESERIALIZER_B_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DESERIALIZER_B_wrapp_0_0/src/DESERIALIZER_B_axi_gpio_0_1/DESERIALIZER_B_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DESERIALIZER_B_axi_gpio_0_1 || ORIG_REF_NAME==DESERIALIZER_B_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_xlconstant_0_0/SP_OV_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_xlconstant_0_0 || ORIG_REF_NAME==SP_OV_xlconstant_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_xlconcat_0_0/SP_OV_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_xlconcat_0_0 || ORIG_REF_NAME==SP_OV_xlconcat_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_xbar_1/SP_OV_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_xbar_1 || ORIG_REF_NAME==SP_OV_xbar_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_axi_interconnect_0_1/SP_OV_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_axi_interconnect_0_1 || ORIG_REF_NAME==SP_OV_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_xlconstant_1_0/SP_OV_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_xlconstant_1_0 || ORIG_REF_NAME==SP_OV_xlconstant_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_tier2_xbar_0_0/SP_OV_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_tier2_xbar_0_0 || ORIG_REF_NAME==SP_OV_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_tier2_xbar_1_0/SP_OV_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_tier2_xbar_1_0 || ORIG_REF_NAME==SP_OV_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_tier2_xbar_2_0/SP_OV_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_tier2_xbar_2_0 || ORIG_REF_NAME==SP_OV_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_tier2_xbar_3_0/SP_OV_tier2_xbar_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_tier2_xbar_3_0 || ORIG_REF_NAME==SP_OV_tier2_xbar_3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_auto_pc_0/SP_OV_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_auto_pc_0 || ORIG_REF_NAME==SP_OV_auto_pc_0} -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_processing_system7_0_0/SP_OV_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_processing_system7_0_0 || ORIG_REF_NAME==SP_OV_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_rst_ps7_0_100M_0/SP_OV_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==SP_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_rst_ps7_0_100M_0/SP_OV_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==SP_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data_0/P_COUNTER_axi_gpio_data_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data_0/P_COUNTER_axi_gpio_data_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data_0/P_COUNTER_axi_gpio_data_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data1_0/P_COUNTER_axi_gpio_data1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data1_0/P_COUNTER_axi_gpio_data1_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data1_0/P_COUNTER_axi_gpio_data1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data2_0/P_COUNTER_axi_gpio_data2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data2_0/P_COUNTER_axi_gpio_data2_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data2_0/P_COUNTER_axi_gpio_data2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data3_0/P_COUNTER_axi_gpio_data3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data3_0/P_COUNTER_axi_gpio_data3_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data3_0/P_COUNTER_axi_gpio_data3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util_0/P_COUNTER_axi_gpio_util_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util_0/P_COUNTER_axi_gpio_util_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util_0/P_COUNTER_axi_gpio_util_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util1_0/P_COUNTER_axi_gpio_util1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util1_0/P_COUNTER_axi_gpio_util1_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util1_0/P_COUNTER_axi_gpio_util1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util2_0/P_COUNTER_axi_gpio_util2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util2_0/P_COUNTER_axi_gpio_util2_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util2_0/P_COUNTER_axi_gpio_util2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util3_0/P_COUNTER_axi_gpio_util3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util3_0/P_COUNTER_axi_gpio_util3_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util3_0/P_COUNTER_axi_gpio_util3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_COM_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_0/DDS_AXI_PERIPH_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_0/DDS_AXI_PERIPH_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_0/DDS_AXI_PERIPH_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_0_0/DDS_AXI_PERIPH_phase_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_0_0/DDS_AXI_PERIPH_phase_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_0_0/DDS_AXI_PERIPH_phase_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_1_0/DDS_AXI_PERIPH_phase_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_1_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_1_0/DDS_AXI_PERIPH_phase_1_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_1_0/DDS_AXI_PERIPH_phase_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_1_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_2_0/DDS_AXI_PERIPH_phase_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_2_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_2_0/DDS_AXI_PERIPH_phase_2_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_2_0/DDS_AXI_PERIPH_phase_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_2_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_1/DDS_AXI_PERIPH_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_1/DDS_AXI_PERIPH_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_1/DDS_AXI_PERIPH_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_0_1/DDS_AXI_PERIPH_aux_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_0_1/DDS_AXI_PERIPH_aux_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_0_1/DDS_AXI_PERIPH_aux_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_1_1/DDS_AXI_PERIPH_aux_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_1_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_1_1/DDS_AXI_PERIPH_aux_1_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_1_1/DDS_AXI_PERIPH_aux_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_1_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_2_1/DDS_AXI_PERIPH_aux_2_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_2_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_2_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_2_1/DDS_AXI_PERIPH_aux_2_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_2_1/DDS_AXI_PERIPH_aux_2_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_2_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_2_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_2/DDS_AXI_PERIPH_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_2/DDS_AXI_PERIPH_axi_gpio_0_2_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_2/DDS_AXI_PERIPH_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_axi_gpio_0_0/SP_OV_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_axi_gpio_0_0 || ORIG_REF_NAME==SP_OV_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_axi_gpio_0_0/SP_OV_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_axi_gpio_0_0/SP_OV_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_axi_gpio_0_0 || ORIG_REF_NAME==SP_OV_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_axi_gpio_0_1/SP_OV_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_axi_gpio_0_1 || ORIG_REF_NAME==SP_OV_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_axi_gpio_0_1/SP_OV_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_axi_gpio_0_1/SP_OV_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_axi_gpio_0_1 || ORIG_REF_NAME==SP_OV_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_0_1/SP_OV_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_0_1 || ORIG_REF_NAME==SP_OV_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_0_1/SP_OV_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_0_1 || ORIG_REF_NAME==SP_OV_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_0_1/SP_OV_clk_wiz_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_1_1/SP_OV_clk_wiz_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_1_1 || ORIG_REF_NAME==SP_OV_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_1_1/SP_OV_clk_wiz_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_1_1 || ORIG_REF_NAME==SP_OV_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_1_1/SP_OV_clk_wiz_1_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_axi_gpio_0_0/SDDR_AXI_ST_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_axi_gpio_0_0 || ORIG_REF_NAME==SDDR_AXI_ST_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_axi_gpio_0_0/SDDR_AXI_ST_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_axi_gpio_0_0/SDDR_AXI_ST_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_axi_gpio_0_0 || ORIG_REF_NAME==SDDR_AXI_ST_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_axi_gpio_0_1/SDDR_AXI_ST_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_axi_gpio_0_1 || ORIG_REF_NAME==SDDR_AXI_ST_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_axi_gpio_0_1/SDDR_AXI_ST_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_axi_gpio_0_1/SDDR_AXI_ST_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_axi_gpio_0_1 || ORIG_REF_NAME==SDDR_AXI_ST_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_AXI_ST_wrapper_0_0/src/SDDR_AXI_ST_fifo_generator_0_0/SDDR_AXI_ST_fifo_generator_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_AXI_ST_fifo_generator_0_0 || ORIG_REF_NAME==SDDR_AXI_ST_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_axi_gpio_0_0/SDDR_CT_AXI_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_axi_gpio_0_0 || ORIG_REF_NAME==SDDR_CT_AXI_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_axi_gpio_0_0/SDDR_CT_AXI_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_axi_gpio_0_0/SDDR_CT_AXI_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_axi_gpio_0_0 || ORIG_REF_NAME==SDDR_CT_AXI_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_axi_gpio_0_1/SDDR_CT_AXI_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_axi_gpio_0_1 || ORIG_REF_NAME==SDDR_CT_AXI_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_axi_gpio_0_1/SDDR_CT_AXI_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_axi_gpio_0_1/SDDR_CT_AXI_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_axi_gpio_0_1 || ORIG_REF_NAME==SDDR_CT_AXI_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_CT_AXI_wrapper_0_0/src/SDDR_CT_AXI_fifo_generator_0_0/SDDR_CT_AXI_fifo_generator_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_CT_AXI_fifo_generator_0_0 || ORIG_REF_NAME==SDDR_CT_AXI_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_0/SDDR_TT_AXI_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_axi_gpio_0_0 || ORIG_REF_NAME==SDDR_TT_AXI_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_0/SDDR_TT_AXI_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_0/SDDR_TT_AXI_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_axi_gpio_0_0 || ORIG_REF_NAME==SDDR_TT_AXI_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_DATA0_0/SDDR_TT_AXI_DATA0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_DATA0_0 || ORIG_REF_NAME==SDDR_TT_AXI_DATA0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_DATA0_0/SDDR_TT_AXI_DATA0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_DATA0_0/SDDR_TT_AXI_DATA0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_DATA0_0 || ORIG_REF_NAME==SDDR_TT_AXI_DATA0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_1/SDDR_TT_AXI_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_axi_gpio_0_1 || ORIG_REF_NAME==SDDR_TT_AXI_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_1/SDDR_TT_AXI_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_1/SDDR_TT_AXI_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_axi_gpio_0_1 || ORIG_REF_NAME==SDDR_TT_AXI_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_2/SDDR_TT_AXI_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_axi_gpio_0_2 || ORIG_REF_NAME==SDDR_TT_AXI_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_2/SDDR_TT_AXI_axi_gpio_0_2_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_2/SDDR_TT_AXI_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_axi_gpio_0_2 || ORIG_REF_NAME==SDDR_TT_AXI_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_3/SDDR_TT_AXI_axi_gpio_0_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_axi_gpio_0_3 || ORIG_REF_NAME==SDDR_TT_AXI_axi_gpio_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_3/SDDR_TT_AXI_axi_gpio_0_3_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_axi_gpio_0_3/SDDR_TT_AXI_axi_gpio_0_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_axi_gpio_0_3 || ORIG_REF_NAME==SDDR_TT_AXI_axi_gpio_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_fifo_generator_0_0/SDDR_TT_AXI_fifo_generator_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDDR_TT_AXI_fifo_generator_0_0 || ORIG_REF_NAME==SDDR_TT_AXI_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_SDDR_TT_AXI_wrapper_0_0/src/SDDR_TT_AXI_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_0_2/SP_OV_clk_wiz_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_0_2 || ORIG_REF_NAME==SP_OV_clk_wiz_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_0_2/SP_OV_clk_wiz_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_0_2 || ORIG_REF_NAME==SP_OV_clk_wiz_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_0_2/SP_OV_clk_wiz_0_2_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DESERIALIZER_B_wrapp_0_0/src/DESERIALIZER_B_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DESERIALIZER_B_wrapp_0_0/src/DESERIALIZER_B_axi_gpio_0_0/DESERIALIZER_B_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DESERIALIZER_B_axi_gpio_0_0 || ORIG_REF_NAME==DESERIALIZER_B_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DESERIALIZER_B_wrapp_0_0/src/DESERIALIZER_B_axi_gpio_0_0/DESERIALIZER_B_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DESERIALIZER_B_wrapp_0_0/src/DESERIALIZER_B_axi_gpio_0_0/DESERIALIZER_B_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DESERIALIZER_B_axi_gpio_0_0 || ORIG_REF_NAME==DESERIALIZER_B_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DESERIALIZER_B_wrapp_0_0/src/DESERIALIZER_B_axi_gpio_0_1/DESERIALIZER_B_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DESERIALIZER_B_axi_gpio_0_1 || ORIG_REF_NAME==DESERIALIZER_B_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DESERIALIZER_B_wrapp_0_0/src/DESERIALIZER_B_axi_gpio_0_1/DESERIALIZER_B_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DESERIALIZER_B_wrapp_0_0/src/DESERIALIZER_B_axi_gpio_0_1/DESERIALIZER_B_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DESERIALIZER_B_axi_gpio_0_1 || ORIG_REF_NAME==DESERIALIZER_B_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_auto_pc_0/SP_OV_auto_pc_0_ooc.xdc

# XDC: bd/SP_OV/SP_OV_ooc.xdc
