# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ-Z1.xdc

# Block Designs: bd/SCS_CT_OV/SCS_CT_OV.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_CT_OV || ORIG_REF_NAME==SCS_CT_OV} -quiet] -quiet

# IP: bd/SCS_CT_OV/ip/SCS_CT_OV_processing_system7_0_0/SCS_CT_OV_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_CT_OV_processing_system7_0_0 || ORIG_REF_NAME==SCS_CT_OV_processing_system7_0_0} -quiet] -quiet

# IP: bd/SCS_CT_OV/ip/SCS_CT_OV_axi_gpio_0_0/SCS_CT_OV_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_CT_OV_axi_gpio_0_0 || ORIG_REF_NAME==SCS_CT_OV_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SCS_CT_OV/ip/SCS_CT_OV_ps7_0_axi_periph_0/SCS_CT_OV_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_CT_OV_ps7_0_axi_periph_0 || ORIG_REF_NAME==SCS_CT_OV_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/SCS_CT_OV/ip/SCS_CT_OV_rst_ps7_0_100M_0/SCS_CT_OV_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_CT_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==SCS_CT_OV_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/SCS_CT_OV/ip/SCS_CT_OV_SCS_CT_wrapper_0_0/SCS_CT_OV_SCS_CT_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_CT_OV_SCS_CT_wrapper_0_0 || ORIG_REF_NAME==SCS_CT_OV_SCS_CT_wrapper_0_0} -quiet] -quiet

# IP: bd/SCS_CT_OV/ip/SCS_CT_OV_SCS_CT_wrapper_0_0/src/ph_ctr/ph_ctr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ph_ctr || ORIG_REF_NAME==ph_ctr} -quiet] -quiet

# IP: bd/SCS_CT_OV/ip/SCS_CT_OV_axi_gpio_0_1/SCS_CT_OV_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_CT_OV_axi_gpio_0_1 || ORIG_REF_NAME==SCS_CT_OV_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SCS_CT_OV/ip/SCS_CT_OV_xlconcat_0_0/SCS_CT_OV_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_CT_OV_xlconcat_0_0 || ORIG_REF_NAME==SCS_CT_OV_xlconcat_0_0} -quiet] -quiet

# IP: bd/SCS_CT_OV/ip/SCS_CT_OV_xbar_0/SCS_CT_OV_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_CT_OV_xbar_0 || ORIG_REF_NAME==SCS_CT_OV_xbar_0} -quiet] -quiet

# IP: bd/SCS_CT_OV/ip/SCS_CT_OV_clk_wiz_0_0/SCS_CT_OV_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_CT_OV_clk_wiz_0_0 || ORIG_REF_NAME==SCS_CT_OV_clk_wiz_0_0} -quiet] -quiet

# IP: bd/SCS_CT_OV/ip/SCS_CT_OV_xlconcat_1_0/SCS_CT_OV_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_CT_OV_xlconcat_1_0 || ORIG_REF_NAME==SCS_CT_OV_xlconcat_1_0} -quiet] -quiet

# IP: bd/SCS_CT_OV/ip/SCS_CT_OV_auto_pc_0/SCS_CT_OV_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_CT_OV_auto_pc_0 || ORIG_REF_NAME==SCS_CT_OV_auto_pc_0} -quiet] -quiet

# XDC: bd/SCS_CT_OV/ip/SCS_CT_OV_processing_system7_0_0/SCS_CT_OV_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCS_CT_OV_processing_system7_0_0 || ORIG_REF_NAME==SCS_CT_OV_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SCS_CT_OV/ip/SCS_CT_OV_axi_gpio_0_0/SCS_CT_OV_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCS_CT_OV_axi_gpio_0_0 || ORIG_REF_NAME==SCS_CT_OV_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SCS_CT_OV/ip/SCS_CT_OV_axi_gpio_0_0/SCS_CT_OV_axi_gpio_0_0_ooc.xdc

# XDC: bd/SCS_CT_OV/ip/SCS_CT_OV_axi_gpio_0_0/SCS_CT_OV_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCS_CT_OV_axi_gpio_0_0 || ORIG_REF_NAME==SCS_CT_OV_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SCS_CT_OV/ip/SCS_CT_OV_rst_ps7_0_100M_0/SCS_CT_OV_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCS_CT_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==SCS_CT_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SCS_CT_OV/ip/SCS_CT_OV_rst_ps7_0_100M_0/SCS_CT_OV_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCS_CT_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==SCS_CT_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SCS_CT_OV/ip/SCS_CT_OV_SCS_CT_wrapper_0_0/src/SCS_CT_ooc.xdc

# XDC: bd/SCS_CT_OV/ip/SCS_CT_OV_axi_gpio_0_1/SCS_CT_OV_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCS_CT_OV_axi_gpio_0_1 || ORIG_REF_NAME==SCS_CT_OV_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SCS_CT_OV/ip/SCS_CT_OV_axi_gpio_0_1/SCS_CT_OV_axi_gpio_0_1_ooc.xdc

# XDC: bd/SCS_CT_OV/ip/SCS_CT_OV_axi_gpio_0_1/SCS_CT_OV_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCS_CT_OV_axi_gpio_0_1 || ORIG_REF_NAME==SCS_CT_OV_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SCS_CT_OV/ip/SCS_CT_OV_clk_wiz_0_0/SCS_CT_OV_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCS_CT_OV_clk_wiz_0_0 || ORIG_REF_NAME==SCS_CT_OV_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SCS_CT_OV/ip/SCS_CT_OV_clk_wiz_0_0/SCS_CT_OV_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCS_CT_OV_clk_wiz_0_0 || ORIG_REF_NAME==SCS_CT_OV_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SCS_CT_OV/ip/SCS_CT_OV_clk_wiz_0_0/SCS_CT_OV_clk_wiz_0_0_ooc.xdc

# XDC: bd/SCS_CT_OV/ip/SCS_CT_OV_auto_pc_0/SCS_CT_OV_auto_pc_0_ooc.xdc

# XDC: bd/SCS_CT_OV/SCS_CT_OV_ooc.xdc
