# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/TT_ctr/TT_ctr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_ctr || ORIG_REF_NAME==TT_ctr} -quiet] -quiet
