@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Dec 16 16:00:58 +1300 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto c9320e5a231e4d5db0fa77860acf12eb --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot IODELAY_BLK_TB_behav xil_defaultlib.IODELAY_BLK_TB -log elaborate.log"
call xelab  -wto c9320e5a231e4d5db0fa77860acf12eb --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot IODELAY_BLK_TB_behav xil_defaultlib.IODELAY_BLK_TB -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
