# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ-Z1.xdc

# Block Designs: bd/SP_OV/SP_OV.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV || ORIG_REF_NAME==SP_OV} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_processing_system7_0_0/SP_OV_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_processing_system7_0_0 || ORIG_REF_NAME==SP_OV_processing_system7_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_xbar_0/SP_OV_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_xbar_0 || ORIG_REF_NAME==SP_OV_xbar_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_axi_interconnect_0_0/SP_OV_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_axi_interconnect_0_0 || ORIG_REF_NAME==SP_OV_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_rst_ps7_0_100M_0/SP_OV_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==SP_OV_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_clk_wiz_0_0/SP_OV_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_0_0 || ORIG_REF_NAME==SP_OV_clk_wiz_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/SP_OV_PG_AXI_PERIPH_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_PG_AXI_PERIPH_wrapper_0_0 || ORIG_REF_NAME==SP_OV_PG_AXI_PERIPH_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/counter/counter.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter || ORIG_REF_NAME==counter} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_gpio_0_0/PG_AXI_PERIPH_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_ch_0_0/PG_AXI_PERIPH_axi_ch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_ch_0_0 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_ch_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_ch_0_1/PG_AXI_PERIPH_axi_ch_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_ch_0_1 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_ch_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_ch_0_2/PG_AXI_PERIPH_axi_ch_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_ch_0_2 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_ch_0_2} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_gpio_0_1/PG_AXI_PERIPH_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_delay_0_0/PG_AXI_PERIPH_axi_delay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_delay_0_0 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_delay_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_gpio_0_2/PG_AXI_PERIPH_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_gpio_0_2} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TIMER_CLK_0/SP_OV_TIMER_CLK_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_TIMER_CLK_0 || ORIG_REF_NAME==SP_OV_TIMER_CLK_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_util_vector_logic_0_0/SP_OV_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_util_vector_logic_0_0 || ORIG_REF_NAME==SP_OV_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_util_vector_logic_0_1/SP_OV_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_util_vector_logic_0_1 || ORIG_REF_NAME==SP_OV_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/SP_OV_ST_AXI_PERIPH_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_ST_AXI_PERIPH_wrapper_0_0 || ORIG_REF_NAME==SP_OV_ST_AXI_PERIPH_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_0/ST_AXI_PERIPH_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==ST_AXI_PERIPH_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_1/ST_AXI_PERIPH_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==ST_AXI_PERIPH_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_SCH_IA_wrapper_0_0/ST_AXI_PERIPH_SCH_IA_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_AXI_PERIPH_SCH_IA_wrapper_0_0 || ORIG_REF_NAME==ST_AXI_PERIPH_SCH_IA_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_SCH_IA_wrapper_0_0/src/SCH_IA_c_counter_binary_0_0/SCH_IA_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCH_IA_c_counter_binary_0_0 || ORIG_REF_NAME==SCH_IA_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_SCH_IA_wrapper_0_0/src/SCH_IA_util_vector_logic_1_0/SCH_IA_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCH_IA_util_vector_logic_1_0 || ORIG_REF_NAME==SCH_IA_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/SP_OV_P_COUNTER_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_P_COUNTER_wrapper_0_0 || ORIG_REF_NAME==SP_OV_P_COUNTER_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data_0/P_COUNTER_axi_gpio_data_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data1_0/P_COUNTER_axi_gpio_data1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data2_0/P_COUNTER_axi_gpio_data2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data3_0/P_COUNTER_axi_gpio_data3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util_0/P_COUNTER_axi_gpio_util_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util1_0/P_COUNTER_axi_gpio_util1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util2_0/P_COUNTER_axi_gpio_util2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util3_0/P_COUNTER_axi_gpio_util3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_c_counter_binary_0_0/P_COUNTER_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_c_counter_binary_0_0 || ORIG_REF_NAME==P_COUNTER_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_c_counter_binary_1_0/P_COUNTER_c_counter_binary_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_c_counter_binary_1_0 || ORIG_REF_NAME==P_COUNTER_c_counter_binary_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_c_counter_binary_2_0/P_COUNTER_c_counter_binary_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_c_counter_binary_2_0 || ORIG_REF_NAME==P_COUNTER_c_counter_binary_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_c_counter_binary_3_0/P_COUNTER_c_counter_binary_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_c_counter_binary_3_0 || ORIG_REF_NAME==P_COUNTER_c_counter_binary_3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_0_0/P_COUNTER_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_0_0 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_1_0/P_COUNTER_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_1_0 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_2_0/P_COUNTER_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_2_0 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_3_0/P_COUNTER_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_3_0 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/SP_OV_CT_AXI_PERIPH_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_CT_AXI_PERIPH_wrapper_0_0 || ORIG_REF_NAME==SP_OV_CT_AXI_PERIPH_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/t_counter_0/t_counter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==t_counter_0 || ORIG_REF_NAME==t_counter_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_0/CT_AXI_PERIPH_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CT_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==CT_AXI_PERIPH_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_1/CT_AXI_PERIPH_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CT_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==CT_AXI_PERIPH_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_tier2_xbar_0_0/SP_OV_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_tier2_xbar_0_0 || ORIG_REF_NAME==SP_OV_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_tier2_xbar_1_0/SP_OV_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_tier2_xbar_1_0 || ORIG_REF_NAME==SP_OV_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_tier2_xbar_2_0/SP_OV_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_tier2_xbar_2_0 || ORIG_REF_NAME==SP_OV_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_auto_pc_0/SP_OV_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_auto_pc_0 || ORIG_REF_NAME==SP_OV_auto_pc_0} -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_processing_system7_0_0/SP_OV_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_processing_system7_0_0 || ORIG_REF_NAME==SP_OV_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_rst_ps7_0_100M_0/SP_OV_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==SP_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_rst_ps7_0_100M_0/SP_OV_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==SP_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_0_0/SP_OV_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_0_0 || ORIG_REF_NAME==SP_OV_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_0_0/SP_OV_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_0_0 || ORIG_REF_NAME==SP_OV_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_0_0/SP_OV_clk_wiz_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_gpio_0_0/PG_AXI_PERIPH_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_gpio_0_0/PG_AXI_PERIPH_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_gpio_0_0/PG_AXI_PERIPH_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_ch_0_0/PG_AXI_PERIPH_axi_ch_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_ch_0_0 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_ch_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_ch_0_0/PG_AXI_PERIPH_axi_ch_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_ch_0_0/PG_AXI_PERIPH_axi_ch_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_ch_0_0 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_ch_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_ch_0_1/PG_AXI_PERIPH_axi_ch_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_ch_0_1 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_ch_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_ch_0_1/PG_AXI_PERIPH_axi_ch_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_ch_0_1/PG_AXI_PERIPH_axi_ch_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_ch_0_1 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_ch_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_ch_0_2/PG_AXI_PERIPH_axi_ch_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_ch_0_2 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_ch_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_ch_0_2/PG_AXI_PERIPH_axi_ch_0_2_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_ch_0_2/PG_AXI_PERIPH_axi_ch_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_ch_0_2 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_ch_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_gpio_0_1/PG_AXI_PERIPH_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_gpio_0_1/PG_AXI_PERIPH_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_gpio_0_1/PG_AXI_PERIPH_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_delay_0_0/PG_AXI_PERIPH_axi_delay_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_delay_0_0 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_delay_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_delay_0_0/PG_AXI_PERIPH_axi_delay_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_delay_0_0/PG_AXI_PERIPH_axi_delay_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_delay_0_0 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_delay_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_gpio_0_2/PG_AXI_PERIPH_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_gpio_0_2/PG_AXI_PERIPH_axi_gpio_0_2_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_PG_AXI_PERIPH_wrapper_0_0/src/PG_AXI_PERIPH_axi_gpio_0_2/PG_AXI_PERIPH_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PG_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==PG_AXI_PERIPH_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TIMER_CLK_0/SP_OV_TIMER_CLK_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_TIMER_CLK_0 || ORIG_REF_NAME==SP_OV_TIMER_CLK_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TIMER_CLK_0/SP_OV_TIMER_CLK_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_TIMER_CLK_0 || ORIG_REF_NAME==SP_OV_TIMER_CLK_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TIMER_CLK_0/SP_OV_TIMER_CLK_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_0/ST_AXI_PERIPH_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==ST_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_0/ST_AXI_PERIPH_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_0/ST_AXI_PERIPH_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==ST_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_1/ST_AXI_PERIPH_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==ST_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_1/ST_AXI_PERIPH_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_1/ST_AXI_PERIPH_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==ST_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_SCH_IA_wrapper_0_0/src/SCH_IA_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data_0/P_COUNTER_axi_gpio_data_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data_0/P_COUNTER_axi_gpio_data_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data_0/P_COUNTER_axi_gpio_data_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data1_0/P_COUNTER_axi_gpio_data1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data1_0/P_COUNTER_axi_gpio_data1_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data1_0/P_COUNTER_axi_gpio_data1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data2_0/P_COUNTER_axi_gpio_data2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data2_0/P_COUNTER_axi_gpio_data2_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data2_0/P_COUNTER_axi_gpio_data2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data3_0/P_COUNTER_axi_gpio_data3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data3_0/P_COUNTER_axi_gpio_data3_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data3_0/P_COUNTER_axi_gpio_data3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util_0/P_COUNTER_axi_gpio_util_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util_0/P_COUNTER_axi_gpio_util_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util_0/P_COUNTER_axi_gpio_util_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util1_0/P_COUNTER_axi_gpio_util1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util1_0/P_COUNTER_axi_gpio_util1_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util1_0/P_COUNTER_axi_gpio_util1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util2_0/P_COUNTER_axi_gpio_util2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util2_0/P_COUNTER_axi_gpio_util2_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util2_0/P_COUNTER_axi_gpio_util2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util3_0/P_COUNTER_axi_gpio_util3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util3_0/P_COUNTER_axi_gpio_util3_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util3_0/P_COUNTER_axi_gpio_util3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_0/CT_AXI_PERIPH_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CT_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==CT_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_0/CT_AXI_PERIPH_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_0/CT_AXI_PERIPH_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CT_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==CT_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_1/CT_AXI_PERIPH_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CT_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==CT_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_1/CT_AXI_PERIPH_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_1/CT_AXI_PERIPH_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CT_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==CT_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_tier2_xbar_0_0/SP_OV_tier2_xbar_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_tier2_xbar_1_0/SP_OV_tier2_xbar_1_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_tier2_xbar_2_0/SP_OV_tier2_xbar_2_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_auto_pc_0/SP_OV_auto_pc_0_ooc.xdc

# XDC: bd/SP_OV/SP_OV_ooc.xdc
