@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Dec 23 10:56:09 +1300 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 1820e369ae18498a91ed52b5843c3165 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot CDELAY_TB_behav xil_defaultlib.CDELAY_TB -log elaborate.log"
call xelab  -wto 1820e369ae18498a91ed52b5843c3165 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot CDELAY_TB_behav xil_defaultlib.CDELAY_TB -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
