@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Jan 24 12:01:46 +1300 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim ST_TEST_wrapper_time_impl -key {Post-Implementation:sim_1:Timing:ST_TEST_wrapper} -tclbatch ST_TEST_wrapper.tcl -protoinst "protoinst_files/SDOS_ST.protoinst" -protoinst "protoinst_files/ST_TEST.protoinst" -log simulate.log"
call xsim  ST_TEST_wrapper_time_impl -key {Post-Implementation:sim_1:Timing:ST_TEST_wrapper} -tclbatch ST_TEST_wrapper.tcl -protoinst "protoinst_files/SDOS_ST.protoinst" -protoinst "protoinst_files/ST_TEST.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
