# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ-Z1.xdc

# Block Designs: bd/DSCH_AXI_PERIPH/DSCH_AXI_PERIPH.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH || ORIG_REF_NAME==DSCH_AXI_PERIPH} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_DSCH_BD_wrapper_0_0/DSCH_AXI_PERIPH_DSCH_BD_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_DSCH_BD_wrapper_0_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_DSCH_BD_wrapper_0_0} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_DSCH_BD_wrapper_0_0/src/DSCH_TIMER/DSCH_TIMER.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_TIMER || ORIG_REF_NAME==DSCH_TIMER} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_DSCH_BD_wrapper_0_0/src/DSCH_BD_DELAYLINE_wrapper_0_0/DSCH_BD_DELAYLINE_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_BD_DELAYLINE_wrapper_0_0 || ORIG_REF_NAME==DSCH_BD_DELAYLINE_wrapper_0_0} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_DSCH_BD_wrapper_0_0/src/DSCH_BD_DELAYLINE_wrapper_0_0/src/DSCH_TIMER/DSCH_TIMER.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_TIMER || ORIG_REF_NAME==DSCH_TIMER} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_DSCH_BD_wrapper_0_0/src/DSCH_BD_xlslice_0_0/DSCH_BD_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_BD_xlslice_0_0 || ORIG_REF_NAME==DSCH_BD_xlslice_0_0} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_DSCH_BD_wrapper_0_0/src/DSCH_BD_xlconstant_0_0/DSCH_BD_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_BD_xlconstant_0_0 || ORIG_REF_NAME==DSCH_BD_xlconstant_0_0} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_processing_system7_0_0/DSCH_AXI_PERIPH_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_processing_system7_0_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_processing_system7_0_0} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_axi_gpio_0_0/DSCH_AXI_PERIPH_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_xlconcat_0_0/DSCH_AXI_PERIPH_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_xlconcat_0_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_xlconcat_0_0} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_xbar_0/DSCH_AXI_PERIPH_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_xbar_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_xbar_0} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_ps7_0_axi_periph_0/DSCH_AXI_PERIPH_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_ps7_0_axi_periph_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_rst_ps7_0_100M_0/DSCH_AXI_PERIPH_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_rst_ps7_0_100M_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_clk_wiz_0_0/DSCH_AXI_PERIPH_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_clk_wiz_0_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_clk_wiz_0_0} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_axi_gpio_0_1/DSCH_AXI_PERIPH_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==DSCH_AXI_PERIPH_axi_gpio_0_1} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_clk_wiz_0_1/DSCH_AXI_PERIPH_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_clk_wiz_0_1 || ORIG_REF_NAME==DSCH_AXI_PERIPH_clk_wiz_0_1} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_IDELAY_CTRL_WRAPPER_0_0/DSCH_AXI_PERIPH_IDELAY_CTRL_WRAPPER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_IDELAY_CTRL_WRAPPER_0_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_IDELAY_CTRL_WRAPPER_0_0} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_Temptest_0_0/DSCH_AXI_PERIPH_Temptest_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_Temptest_0_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_Temptest_0_0} -quiet] -quiet

# IP: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_auto_pc_0/DSCH_AXI_PERIPH_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_auto_pc_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_auto_pc_0} -quiet] -quiet

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_DSCH_BD_wrapper_0_0/src/DSCH_BD_DELAYLINE_wrapper_0_0/src/DELAYLINE_ooc.xdc

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_DSCH_BD_wrapper_0_0/src/DSCH_BD_ooc.xdc

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_processing_system7_0_0/DSCH_AXI_PERIPH_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_processing_system7_0_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_axi_gpio_0_0/DSCH_AXI_PERIPH_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_axi_gpio_0_0/DSCH_AXI_PERIPH_axi_gpio_0_0_ooc.xdc

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_axi_gpio_0_0/DSCH_AXI_PERIPH_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_rst_ps7_0_100M_0/DSCH_AXI_PERIPH_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_rst_ps7_0_100M_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_rst_ps7_0_100M_0/DSCH_AXI_PERIPH_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_rst_ps7_0_100M_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_clk_wiz_0_0/DSCH_AXI_PERIPH_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_clk_wiz_0_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_clk_wiz_0_0/DSCH_AXI_PERIPH_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_clk_wiz_0_0 || ORIG_REF_NAME==DSCH_AXI_PERIPH_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_clk_wiz_0_0/DSCH_AXI_PERIPH_clk_wiz_0_0_ooc.xdc

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_axi_gpio_0_1/DSCH_AXI_PERIPH_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==DSCH_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_axi_gpio_0_1/DSCH_AXI_PERIPH_axi_gpio_0_1_ooc.xdc

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_axi_gpio_0_1/DSCH_AXI_PERIPH_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==DSCH_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_clk_wiz_0_1/DSCH_AXI_PERIPH_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_clk_wiz_0_1 || ORIG_REF_NAME==DSCH_AXI_PERIPH_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_clk_wiz_0_1/DSCH_AXI_PERIPH_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DSCH_AXI_PERIPH_clk_wiz_0_1 || ORIG_REF_NAME==DSCH_AXI_PERIPH_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_clk_wiz_0_1/DSCH_AXI_PERIPH_clk_wiz_0_1_ooc.xdc

# XDC: bd/DSCH_AXI_PERIPH/ip/DSCH_AXI_PERIPH_auto_pc_0/DSCH_AXI_PERIPH_auto_pc_0_ooc.xdc

# XDC: bd/DSCH_AXI_PERIPH/DSCH_AXI_PERIPH_ooc.xdc
