set_property PACKAGE_PIN W14 [get_ports T1]
set_property PACKAGE_PIN Y14 [get_ports T2]
set_property IOSTANDARD LVCMOS33 [get_ports T1]
set_property IOSTANDARD LVCMOS33 [get_ports T2]
set_property PACKAGE_PIN N15 [get_ports ARMED]
set_property PACKAGE_PIN M15 [get_ports WAITING]
set_property IOSTANDARD LVCMOS33 [get_ports ARMED]
set_property IOSTANDARD LVCMOS33 [get_ports WAITING]
