# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/CO_AXI_PERIPH/CO_AXI_PERIPH.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CO_AXI_PERIPH || ORIG_REF_NAME==CO_AXI_PERIPH} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_0/CO_AXI_PERIPH_COUNTER_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CO_AXI_PERIPH_COUNTER_wrapper_0_0 || ORIG_REF_NAME==CO_AXI_PERIPH_COUNTER_wrapper_0_0} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_0/src/COUNTER_c_counter_binary_0_0/COUNTER_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_c_counter_binary_0_0 || ORIG_REF_NAME==COUNTER_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_0/src/COUNTER_util_vector_logic_0_0/COUNTER_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_util_vector_logic_0_0 || ORIG_REF_NAME==COUNTER_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_1/CO_AXI_PERIPH_COUNTER_wrapper_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CO_AXI_PERIPH_COUNTER_wrapper_0_1 || ORIG_REF_NAME==CO_AXI_PERIPH_COUNTER_wrapper_0_1} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_1/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_1/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_1/src/COUNTER_c_counter_binary_0_0/COUNTER_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_c_counter_binary_0_0 || ORIG_REF_NAME==COUNTER_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_1/src/COUNTER_util_vector_logic_0_0/COUNTER_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_util_vector_logic_0_0 || ORIG_REF_NAME==COUNTER_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_0/CO_AXI_PERIPH_COUNTER_wrapper_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CO_AXI_PERIPH_COUNTER_wrapper_1_0 || ORIG_REF_NAME==CO_AXI_PERIPH_COUNTER_wrapper_1_0} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_0/src/COUNTER_c_counter_binary_0_0/COUNTER_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_c_counter_binary_0_0 || ORIG_REF_NAME==COUNTER_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_0/src/COUNTER_util_vector_logic_0_0/COUNTER_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_util_vector_logic_0_0 || ORIG_REF_NAME==COUNTER_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_1/CO_AXI_PERIPH_COUNTER_wrapper_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CO_AXI_PERIPH_COUNTER_wrapper_1_1 || ORIG_REF_NAME==CO_AXI_PERIPH_COUNTER_wrapper_1_1} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_1/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_1/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_1/src/COUNTER_c_counter_binary_0_0/COUNTER_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_c_counter_binary_0_0 || ORIG_REF_NAME==COUNTER_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_1/src/COUNTER_util_vector_logic_0_0/COUNTER_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_util_vector_logic_0_0 || ORIG_REF_NAME==COUNTER_util_vector_logic_0_0} -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_ooc.xdc

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_ooc.xdc

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_0/src/COUNTER_ooc.xdc

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_1/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_1/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_ooc.xdc

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_1/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_1/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_1/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_ooc.xdc

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_1/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_0_1/src/COUNTER_ooc.xdc

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_ooc.xdc

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_0/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_ooc.xdc

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_0/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_0/src/COUNTER_ooc.xdc

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_1/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_1/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_ooc.xdc

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_1/src/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_1/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_1/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_ooc.xdc

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_1/src/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CO_AXI_PERIPH/ip/CO_AXI_PERIPH_COUNTER_wrapper_1_1/src/COUNTER_ooc.xdc

# XDC: bd/CO_AXI_PERIPH/CO_AXI_PERIPH_ooc.xdc
