# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ-Z1.xdc

# Block Designs: bd/HS_SAMPLER_OVERLAY/HS_SAMPLER_OVERLAY.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY || ORIG_REF_NAME==HS_SAMPLER_OVERLAY} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_processing_system7_0_0/HS_SAMPLER_OVERLAY_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_processing_system7_0_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_processing_system7_0_0} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_axi_gpio_0_0/HS_SAMPLER_OVERLAY_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_axi_gpio_0_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_axi_gpio_0_0} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_ps7_0_axi_periph_0/HS_SAMPLER_OVERLAY_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_ps7_0_axi_periph_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_rst_ps7_0_100M_0/HS_SAMPLER_OVERLAY_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_rst_ps7_0_100M_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_clk_wiz_0_0/HS_SAMPLER_OVERLAY_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_clk_wiz_0_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_clk_wiz_0_0} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_selectio_wiz_0_0/HS_SAMPLER_OVERLAY_selectio_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_selectio_wiz_0_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_selectio_wiz_0_0} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_clk_wiz_1_0/HS_SAMPLER_OVERLAY_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_clk_wiz_1_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_clk_wiz_1_0} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_util_vector_logic_0_0/HS_SAMPLER_OVERLAY_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_util_vector_logic_0_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_xbar_0/HS_SAMPLER_OVERLAY_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_xbar_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_xbar_0} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_axi_gpio_1_0/HS_SAMPLER_OVERLAY_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_axi_gpio_1_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_axi_gpio_1_0} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_PARALLELIZERTO6_0_0/HS_SAMPLER_OVERLAY_PARALLELIZERTO6_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_PARALLELIZERTO6_0_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_PARALLELIZERTO6_0_0} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_xlslice_0_0/HS_SAMPLER_OVERLAY_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_xlslice_0_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_xlslice_0_0} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_xlslice_0_1/HS_SAMPLER_OVERLAY_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_xlslice_0_1 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_xlslice_0_1} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_xlslice_1_0/HS_SAMPLER_OVERLAY_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_xlslice_1_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_xlslice_1_0} -quiet] -quiet

# IP: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_auto_pc_0/HS_SAMPLER_OVERLAY_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_auto_pc_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_auto_pc_0} -quiet] -quiet

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_processing_system7_0_0/HS_SAMPLER_OVERLAY_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_processing_system7_0_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_axi_gpio_0_0/HS_SAMPLER_OVERLAY_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_axi_gpio_0_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_axi_gpio_0_0/HS_SAMPLER_OVERLAY_axi_gpio_0_0_ooc.xdc

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_axi_gpio_0_0/HS_SAMPLER_OVERLAY_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_axi_gpio_0_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_rst_ps7_0_100M_0/HS_SAMPLER_OVERLAY_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_rst_ps7_0_100M_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_rst_ps7_0_100M_0/HS_SAMPLER_OVERLAY_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_rst_ps7_0_100M_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_clk_wiz_0_0/HS_SAMPLER_OVERLAY_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_clk_wiz_0_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_clk_wiz_0_0/HS_SAMPLER_OVERLAY_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_clk_wiz_0_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_clk_wiz_0_0/HS_SAMPLER_OVERLAY_clk_wiz_0_0_ooc.xdc

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_selectio_wiz_0_0/HS_SAMPLER_OVERLAY_selectio_wiz_0_0_ooc.xdc

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_selectio_wiz_0_0/HS_SAMPLER_OVERLAY_selectio_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_selectio_wiz_0_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_selectio_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_clk_wiz_1_0/HS_SAMPLER_OVERLAY_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_clk_wiz_1_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_clk_wiz_1_0/HS_SAMPLER_OVERLAY_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_clk_wiz_1_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_clk_wiz_1_0/HS_SAMPLER_OVERLAY_clk_wiz_1_0_ooc.xdc

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_axi_gpio_1_0/HS_SAMPLER_OVERLAY_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_axi_gpio_1_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_axi_gpio_1_0/HS_SAMPLER_OVERLAY_axi_gpio_1_0_ooc.xdc

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_axi_gpio_1_0/HS_SAMPLER_OVERLAY_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HS_SAMPLER_OVERLAY_axi_gpio_1_0 || ORIG_REF_NAME==HS_SAMPLER_OVERLAY_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/HS_SAMPLER_OVERLAY/ip/HS_SAMPLER_OVERLAY_auto_pc_0/HS_SAMPLER_OVERLAY_auto_pc_0_ooc.xdc

# XDC: bd/HS_SAMPLER_OVERLAY/HS_SAMPLER_OVERLAY_ooc.xdc
