# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/SCS_TT_CTR/SCS_TT_CTR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_TT_CTR || ORIG_REF_NAME==SCS_TT_CTR} -quiet] -quiet

# Block Designs: bd/SCS_TT/SCS_TT.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_TT || ORIG_REF_NAME==SCS_TT} -quiet] -quiet

# IP: bd/SCS_TT/ip/SCS_TT_TT_CDELAY_0_0/SCS_TT_TT_CDELAY_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_TT_TT_CDELAY_0_0 || ORIG_REF_NAME==SCS_TT_TT_CDELAY_0_0} -quiet] -quiet

# IP: bd/SCS_TT/ip/SCS_TT_TT_CDELAY_0_1/SCS_TT_TT_CDELAY_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_TT_TT_CDELAY_0_1 || ORIG_REF_NAME==SCS_TT_TT_CDELAY_0_1} -quiet] -quiet

# IP: bd/SCS_TT/ip/SCS_TT_TT_CDELAY_1_0/SCS_TT_TT_CDELAY_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_TT_TT_CDELAY_1_0 || ORIG_REF_NAME==SCS_TT_TT_CDELAY_1_0} -quiet] -quiet

# IP: bd/SCS_TT/ip/SCS_TT_TT_CDELAY_2_0/SCS_TT_TT_CDELAY_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_TT_TT_CDELAY_2_0 || ORIG_REF_NAME==SCS_TT_TT_CDELAY_2_0} -quiet] -quiet

# IP: bd/SCS_TT/ip/SCS_TT_TT_CDELAY_2_1/SCS_TT_TT_CDELAY_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_TT_TT_CDELAY_2_1 || ORIG_REF_NAME==SCS_TT_TT_CDELAY_2_1} -quiet] -quiet

# IP: bd/SCS_TT/ip/SCS_TT_TT_DETECTOR_0_0/SCS_TT_TT_DETECTOR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_TT_TT_DETECTOR_0_0 || ORIG_REF_NAME==SCS_TT_TT_DETECTOR_0_0} -quiet] -quiet

# IP: ip/SCS_TT_CTR/SCS_TT_CTR.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCS_TT_CTR || ORIG_REF_NAME==SCS_TT_CTR} -quiet] -quiet

# XDC: bd/SCS_TT/SCS_TT_ooc.xdc
