set_property PACKAGE_PIN W14 [get_ports INPUT_PULSE]
set_property IOSTANDARD LVCMOS33 [get_ports INPUT_PULSE]
set_property PACKAGE_PIN V16 [get_ports OUT0]
set_property IOSTANDARD LVCMOS33 [get_ports OUT0]
set_property PACKAGE_PIN W16 [get_ports OUT1]
set_property IOSTANDARD LVCMOS33 [get_ports OUT1]

set_property IOSTANDARD LVCMOS33 [get_ports RDY]
set_property PACKAGE_PIN N15 [get_ports RDY]

set_property SLEW FAST [get_ports OUT0]
set_property SLEW FAST [get_ports OUT1]
set_property DRIVE 16 [get_ports OUT1]
set_property DRIVE 16 [get_ports OUT0]
set_property PULLDOWN true [get_ports OUT0]
set_property PULLDOWN true [get_ports OUT1]
