# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/COUNTER/COUNTER.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER || ORIG_REF_NAME==COUNTER} -quiet] -quiet

# IP: bd/COUNTER/ip/COUNTER_DIG_TIMER_0_0/COUNTER_DIG_TIMER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_DIG_TIMER_0_0 || ORIG_REF_NAME==COUNTER_DIG_TIMER_0_0} -quiet] -quiet

# IP: bd/COUNTER/ip/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] -quiet

# IP: bd/COUNTER/ip/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] -quiet

# IP: bd/COUNTER/ip/COUNTER_PULSE_COUNTER_0_1/COUNTER_PULSE_COUNTER_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==COUNTER_PULSE_COUNTER_0_1 || ORIG_REF_NAME==COUNTER_PULSE_COUNTER_0_1} -quiet] -quiet

# XDC: bd/COUNTER/ip/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/COUNTER/ip/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0_ooc.xdc

# XDC: bd/COUNTER/ip/COUNTER_axi_gpio_0_0/COUNTER_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_0 || ORIG_REF_NAME==COUNTER_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/COUNTER/ip/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/COUNTER/ip/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1_ooc.xdc

# XDC: bd/COUNTER/ip/COUNTER_axi_gpio_0_1/COUNTER_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==COUNTER_axi_gpio_0_1 || ORIG_REF_NAME==COUNTER_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/COUNTER/COUNTER_ooc.xdc
