set_property PACKAGE_PIN Y18 [get_ports T0]
set_property PACKAGE_PIN W14 [get_ports T1]
set_property PACKAGE_PIN Y14 [get_ports T2]
set_property PACKAGE_PIN T11 [get_ports T3]
set_property PACKAGE_PIN T10 [get_ports T4]
set_property IOSTANDARD LVCMOS33 [get_ports T0]
set_property IOSTANDARD LVCMOS33 [get_ports T1]
set_property IOSTANDARD LVCMOS33 [get_ports T2]
set_property IOSTANDARD LVCMOS33 [get_ports T3]
set_property IOSTANDARD LVCMOS33 [get_ports T4]

set_property PACKAGE_PIN G17 [get_ports WAITING]
set_property PACKAGE_PIN M15 [get_ports LISTENING]
set_property IOSTANDARD LVCMOS33 [get_ports LISTENING]
set_property IOSTANDARD LVCMOS33 [get_ports WAITING]
