@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Dec 02 09:51:54 +1300 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim GEN_CORE_TB_behav -key {Behavioral:sim_1:Functional:GEN_CORE_TB} -tclbatch GEN_CORE_TB.tcl -log simulate.log"
call xsim  GEN_CORE_TB_behav -key {Behavioral:sim_1:Functional:GEN_CORE_TB} -tclbatch GEN_CORE_TB.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
