set_property PACKAGE_PIN N15 [get_ports ARMED]
set_property PACKAGE_PIN M15 [get_ports WAITING]
set_property PACKAGE_PIN W14 [get_ports P0]
set_property PACKAGE_PIN Y14 [get_ports P1]
set_property PACKAGE_PIN T11 [get_ports P2]
set_property PACKAGE_PIN T10 [get_ports P3]
set_property IOSTANDARD LVCMOS33 [get_ports ARMED]
set_property IOSTANDARD LVCMOS33 [get_ports P0]
set_property IOSTANDARD LVCMOS33 [get_ports P1]
set_property IOSTANDARD LVCMOS33 [get_ports P2]
set_property IOSTANDARD LVCMOS33 [get_ports P3]
set_property IOSTANDARD LVCMOS33 [get_ports WAITING]




set_property IOSTANDARD LVCMOS33 [get_ports {LOCKED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LOCKED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LOCKED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LOCKED[3]}]
set_property PACKAGE_PIN R14 [get_ports {LOCKED[0]}]
set_property PACKAGE_PIN P14 [get_ports {LOCKED[1]}]
set_property PACKAGE_PIN N16 [get_ports {LOCKED[2]}]
set_property PACKAGE_PIN M14 [get_ports {LOCKED[3]}]
set_property PACKAGE_PIN H16 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
