# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/SInglePhotons/Vivado Projects/TIME_TAG_N/TIME_TAG_N.cache/wt} [current_project]
set_property parent.project_path {D:/SInglePhotons/Vivado Projects/TIME_TAG_N/TIME_TAG_N.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths d:/SInglePhotons/HW_IP/TIME_TAGGER [current_project]
update_ip_catalog
set_property ip_output_repo {d:/SInglePhotons/Vivado Projects/TIME_TAG_N/TIME_TAG_N.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{D:/SInglePhotons/Vivado Projects/TIME_TAG_N/TIME_TAG_N.srcs/sources_1/new/TIME_TAG_M.vhd}}
read_ip -quiet {{D:/SInglePhotons/Vivado Projects/TIME_TAG_N/TIME_TAG_N.srcs/sources_1/ip/TT_ctr/TT_ctr.xci}}

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TIME_TAG_M -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TIME_TAG_M.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TIME_TAG_M_utilization_synth.rpt -pb TIME_TAG_M_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
