# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ-Z1.xdc

# Block Designs: bd/DDS_COM_OV/DDS_COM_OV.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_OV || ORIG_REF_NAME==DDS_COM_OV} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_processing_system7_0_0/DDS_COM_OV_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_OV_processing_system7_0_0 || ORIG_REF_NAME==DDS_COM_OV_processing_system7_0_0} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_axi_gpio_0_0/DDS_COM_OV_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_OV_axi_gpio_0_0 || ORIG_REF_NAME==DDS_COM_OV_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_rst_ps7_0_100M_0/DDS_COM_OV_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==DDS_COM_OV_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_xbar_1/DDS_COM_OV_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_OV_xbar_1 || ORIG_REF_NAME==DDS_COM_OV_xbar_1} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_ps7_0_axi_periph_0/DDS_COM_OV_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_OV_ps7_0_axi_periph_0 || ORIG_REF_NAME==DDS_COM_OV_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_xlconcat_0_0/DDS_COM_OV_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_OV_xlconcat_0_0 || ORIG_REF_NAME==DDS_COM_OV_xlconcat_0_0} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_DDS_COM_wrapper_0_0/DDS_COM_OV_DDS_COM_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_OV_DDS_COM_wrapper_0_0 || ORIG_REF_NAME==DDS_COM_OV_DDS_COM_wrapper_0_0} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_DDS_COM_wrapper_0_0/src/DDS_COM_dds_compiler_0_0/DDS_COM_dds_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_dds_compiler_0_0 || ORIG_REF_NAME==DDS_COM_dds_compiler_0_0} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_DDS_COM_wrapper_0_0/src/DDS_COM_dds_compiler_0_1/DDS_COM_dds_compiler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_dds_compiler_0_1 || ORIG_REF_NAME==DDS_COM_dds_compiler_0_1} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_axi_gpio_0_1/DDS_COM_OV_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_OV_axi_gpio_0_1 || ORIG_REF_NAME==DDS_COM_OV_axi_gpio_0_1} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_xlconcat_0_1/DDS_COM_OV_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_OV_xlconcat_0_1 || ORIG_REF_NAME==DDS_COM_OV_xlconcat_0_1} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_clk_wiz_0_0/DDS_COM_OV_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_OV_clk_wiz_0_0 || ORIG_REF_NAME==DDS_COM_OV_clk_wiz_0_0} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_axi_gpio_2_0/DDS_COM_OV_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_OV_axi_gpio_2_0 || ORIG_REF_NAME==DDS_COM_OV_axi_gpio_2_0} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_split_c_0_0/DDS_COM_OV_split_c_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_OV_split_c_0_0 || ORIG_REF_NAME==DDS_COM_OV_split_c_0_0} -quiet] -quiet

# IP: bd/DDS_COM_OV/ip/DDS_COM_OV_auto_pc_0/DDS_COM_OV_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_OV_auto_pc_0 || ORIG_REF_NAME==DDS_COM_OV_auto_pc_0} -quiet] -quiet

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_processing_system7_0_0/DDS_COM_OV_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_COM_OV_processing_system7_0_0 || ORIG_REF_NAME==DDS_COM_OV_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_axi_gpio_0_0/DDS_COM_OV_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_COM_OV_axi_gpio_0_0 || ORIG_REF_NAME==DDS_COM_OV_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_axi_gpio_0_0/DDS_COM_OV_axi_gpio_0_0_ooc.xdc

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_axi_gpio_0_0/DDS_COM_OV_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_COM_OV_axi_gpio_0_0 || ORIG_REF_NAME==DDS_COM_OV_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_rst_ps7_0_100M_0/DDS_COM_OV_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_COM_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==DDS_COM_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_rst_ps7_0_100M_0/DDS_COM_OV_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_COM_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==DDS_COM_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_DDS_COM_wrapper_0_0/src/DDS_COM_ooc.xdc

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_axi_gpio_0_1/DDS_COM_OV_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_COM_OV_axi_gpio_0_1 || ORIG_REF_NAME==DDS_COM_OV_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_axi_gpio_0_1/DDS_COM_OV_axi_gpio_0_1_ooc.xdc

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_axi_gpio_0_1/DDS_COM_OV_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_COM_OV_axi_gpio_0_1 || ORIG_REF_NAME==DDS_COM_OV_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_clk_wiz_0_0/DDS_COM_OV_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_COM_OV_clk_wiz_0_0 || ORIG_REF_NAME==DDS_COM_OV_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_clk_wiz_0_0/DDS_COM_OV_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_COM_OV_clk_wiz_0_0 || ORIG_REF_NAME==DDS_COM_OV_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_clk_wiz_0_0/DDS_COM_OV_clk_wiz_0_0_ooc.xdc

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_axi_gpio_2_0/DDS_COM_OV_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_COM_OV_axi_gpio_2_0 || ORIG_REF_NAME==DDS_COM_OV_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_axi_gpio_2_0/DDS_COM_OV_axi_gpio_2_0_ooc.xdc

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_axi_gpio_2_0/DDS_COM_OV_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_COM_OV_axi_gpio_2_0 || ORIG_REF_NAME==DDS_COM_OV_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDS_COM_OV/ip/DDS_COM_OV_auto_pc_0/DDS_COM_OV_auto_pc_0_ooc.xdc

# XDC: bd/DDS_COM_OV/DDS_COM_OV_ooc.xdc
