# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ-Z1.xdc

# Block Designs: bd/ST_TEST/ST_TEST.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST || ORIG_REF_NAME==ST_TEST} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_processing_system7_0_0/ST_TEST_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_processing_system7_0_0 || ORIG_REF_NAME==ST_TEST_processing_system7_0_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_clk_wiz_0_0/ST_TEST_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_clk_wiz_0_0 || ORIG_REF_NAME==ST_TEST_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_0/ST_TEST_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_0 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_1/ST_TEST_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_1 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_1} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_xbar_0/ST_TEST_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_xbar_0 || ORIG_REF_NAME==ST_TEST_xbar_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_ps7_0_axi_periph_0/ST_TEST_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_ps7_0_axi_periph_0 || ORIG_REF_NAME==ST_TEST_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_rst_ps7_0_100M_0/ST_TEST_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_rst_ps7_0_100M_0 || ORIG_REF_NAME==ST_TEST_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_2/ST_TEST_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_2 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_2} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_DELAY0_0/ST_TEST_DELAY0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_DELAY0_0 || ORIG_REF_NAME==ST_TEST_DELAY0_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_3/ST_TEST_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_3 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_3} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_4/ST_TEST_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_4 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_4} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_SDDR_ST_0_0/ST_TEST_SDDR_ST_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_SDDR_ST_0_0 || ORIG_REF_NAME==ST_TEST_SDDR_ST_0_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_SDDR_ST_0_0/src/ST_TIMER/ST_TIMER.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TIMER || ORIG_REF_NAME==ST_TIMER} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_xlconcat_0_1/ST_TEST_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_xlconcat_0_1 || ORIG_REF_NAME==ST_TEST_xlconcat_0_1} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_SHUFFLYBOI_0_0/ST_TEST_SHUFFLYBOI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_SHUFFLYBOI_0_0 || ORIG_REF_NAME==ST_TEST_SHUFFLYBOI_0_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_clk_wiz_1_0/ST_TEST_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_clk_wiz_1_0 || ORIG_REF_NAME==ST_TEST_clk_wiz_1_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_clk_wiz_2_0/ST_TEST_clk_wiz_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_clk_wiz_2_0 || ORIG_REF_NAME==ST_TEST_clk_wiz_2_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_xlconcat_1_0/ST_TEST_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_xlconcat_1_0 || ORIG_REF_NAME==ST_TEST_xlconcat_1_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_util_ds_buf_0_0/ST_TEST_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_util_ds_buf_0_0 || ORIG_REF_NAME==ST_TEST_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_selectio_wiz_0_1/ST_TEST_selectio_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_selectio_wiz_0_1 || ORIG_REF_NAME==ST_TEST_selectio_wiz_0_1} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_selectio_wiz_0_2/ST_TEST_selectio_wiz_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_selectio_wiz_0_2 || ORIG_REF_NAME==ST_TEST_selectio_wiz_0_2} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_selectio_wiz_1_0/ST_TEST_selectio_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_selectio_wiz_1_0 || ORIG_REF_NAME==ST_TEST_selectio_wiz_1_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_selectio_wiz_2_0/ST_TEST_selectio_wiz_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_selectio_wiz_2_0 || ORIG_REF_NAME==ST_TEST_selectio_wiz_2_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_util_vector_logic_0_0/ST_TEST_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_util_vector_logic_0_0 || ORIG_REF_NAME==ST_TEST_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_xlconstant_1_0/ST_TEST_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_xlconstant_1_0 || ORIG_REF_NAME==ST_TEST_xlconstant_1_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_METAH_0_0/ST_TEST_METAH_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_METAH_0_0 || ORIG_REF_NAME==ST_TEST_METAH_0_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_xlconstant_1_1/ST_TEST_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_xlconstant_1_1 || ORIG_REF_NAME==ST_TEST_xlconstant_1_1} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_METAH_0_1/ST_TEST_METAH_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_METAH_0_1 || ORIG_REF_NAME==ST_TEST_METAH_0_1} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_METAH_1_0/ST_TEST_METAH_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_METAH_1_0 || ORIG_REF_NAME==ST_TEST_METAH_1_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_METAH_2_0/ST_TEST_METAH_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_METAH_2_0 || ORIG_REF_NAME==ST_TEST_METAH_2_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_METAH_0_2/ST_TEST_METAH_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_METAH_0_2 || ORIG_REF_NAME==ST_TEST_METAH_0_2} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_CLOCK_DELAY_0_0/ST_TEST_CLOCK_DELAY_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_CLOCK_DELAY_0_0 || ORIG_REF_NAME==ST_TEST_CLOCK_DELAY_0_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_xlconcat_2_0/ST_TEST_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_xlconcat_2_0 || ORIG_REF_NAME==ST_TEST_xlconcat_2_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_clock_splitter_0_0/ST_TEST_clock_splitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_clock_splitter_0_0 || ORIG_REF_NAME==ST_TEST_clock_splitter_0_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_IDEL_CTRL_0_0/ST_TEST_IDEL_CTRL_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_IDEL_CTRL_0_0 || ORIG_REF_NAME==ST_TEST_IDEL_CTRL_0_0} -quiet] -quiet

# IP: bd/ST_TEST/ip/ST_TEST_auto_pc_0/ST_TEST_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_TEST_auto_pc_0 || ORIG_REF_NAME==ST_TEST_auto_pc_0} -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_processing_system7_0_0/ST_TEST_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_processing_system7_0_0 || ORIG_REF_NAME==ST_TEST_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_clk_wiz_0_0/ST_TEST_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_clk_wiz_0_0 || ORIG_REF_NAME==ST_TEST_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_clk_wiz_0_0/ST_TEST_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_clk_wiz_0_0 || ORIG_REF_NAME==ST_TEST_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_clk_wiz_0_0/ST_TEST_clk_wiz_0_0_ooc.xdc

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_0/ST_TEST_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_0 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_0/ST_TEST_axi_gpio_0_0_ooc.xdc

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_0/ST_TEST_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_0 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_1/ST_TEST_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_1 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_1/ST_TEST_axi_gpio_0_1_ooc.xdc

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_1/ST_TEST_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_1 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_rst_ps7_0_100M_0/ST_TEST_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_rst_ps7_0_100M_0 || ORIG_REF_NAME==ST_TEST_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_rst_ps7_0_100M_0/ST_TEST_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_rst_ps7_0_100M_0 || ORIG_REF_NAME==ST_TEST_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_2/ST_TEST_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_2 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_2/ST_TEST_axi_gpio_0_2_ooc.xdc

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_2/ST_TEST_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_2 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_DELAY0_0/ST_TEST_DELAY0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_DELAY0_0 || ORIG_REF_NAME==ST_TEST_DELAY0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_DELAY0_0/ST_TEST_DELAY0_0_ooc.xdc

# XDC: bd/ST_TEST/ip/ST_TEST_DELAY0_0/ST_TEST_DELAY0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_DELAY0_0 || ORIG_REF_NAME==ST_TEST_DELAY0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_3/ST_TEST_axi_gpio_0_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_3 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_3/ST_TEST_axi_gpio_0_3_ooc.xdc

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_3/ST_TEST_axi_gpio_0_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_3 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_4/ST_TEST_axi_gpio_0_4_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_4 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_4/ST_TEST_axi_gpio_0_4_ooc.xdc

# XDC: bd/ST_TEST/ip/ST_TEST_axi_gpio_0_4/ST_TEST_axi_gpio_0_4.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_axi_gpio_0_4 || ORIG_REF_NAME==ST_TEST_axi_gpio_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_clk_wiz_1_0/ST_TEST_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_clk_wiz_1_0 || ORIG_REF_NAME==ST_TEST_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_clk_wiz_1_0/ST_TEST_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_clk_wiz_1_0 || ORIG_REF_NAME==ST_TEST_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_clk_wiz_1_0/ST_TEST_clk_wiz_1_0_ooc.xdc

# XDC: bd/ST_TEST/ip/ST_TEST_clk_wiz_2_0/ST_TEST_clk_wiz_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_clk_wiz_2_0 || ORIG_REF_NAME==ST_TEST_clk_wiz_2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_clk_wiz_2_0/ST_TEST_clk_wiz_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_clk_wiz_2_0 || ORIG_REF_NAME==ST_TEST_clk_wiz_2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_clk_wiz_2_0/ST_TEST_clk_wiz_2_0_ooc.xdc

# XDC: bd/ST_TEST/ip/ST_TEST_util_ds_buf_0_0/ST_TEST_util_ds_buf_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_util_ds_buf_0_0 || ORIG_REF_NAME==ST_TEST_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_util_ds_buf_0_0/ST_TEST_util_ds_buf_0_0_ooc.xdc

# XDC: bd/ST_TEST/ip/ST_TEST_selectio_wiz_0_1/ST_TEST_selectio_wiz_0_1_ooc.xdc

# XDC: bd/ST_TEST/ip/ST_TEST_selectio_wiz_0_1/ST_TEST_selectio_wiz_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_selectio_wiz_0_1 || ORIG_REF_NAME==ST_TEST_selectio_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_selectio_wiz_0_2/ST_TEST_selectio_wiz_0_2_ooc.xdc

# XDC: bd/ST_TEST/ip/ST_TEST_selectio_wiz_0_2/ST_TEST_selectio_wiz_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_selectio_wiz_0_2 || ORIG_REF_NAME==ST_TEST_selectio_wiz_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_selectio_wiz_1_0/ST_TEST_selectio_wiz_1_0_ooc.xdc

# XDC: bd/ST_TEST/ip/ST_TEST_selectio_wiz_1_0/ST_TEST_selectio_wiz_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_selectio_wiz_1_0 || ORIG_REF_NAME==ST_TEST_selectio_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_selectio_wiz_2_0/ST_TEST_selectio_wiz_2_0_ooc.xdc

# XDC: bd/ST_TEST/ip/ST_TEST_selectio_wiz_2_0/ST_TEST_selectio_wiz_2_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_TEST_selectio_wiz_2_0 || ORIG_REF_NAME==ST_TEST_selectio_wiz_2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ST_TEST/ip/ST_TEST_auto_pc_0/ST_TEST_auto_pc_0_ooc.xdc

# XDC: bd/ST_TEST/ST_TEST_ooc.xdc
