# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ-Z1.xdc

# Block Designs: bd/PRG_IDELAY/PRG_IDELAY.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PRG_IDELAY || ORIG_REF_NAME==PRG_IDELAY} -quiet] -quiet

# IP: bd/PRG_IDELAY/ip/PRG_IDELAY_IDELAY_BOI_0_0/PRG_IDELAY_IDELAY_BOI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PRG_IDELAY_IDELAY_BOI_0_0 || ORIG_REF_NAME==PRG_IDELAY_IDELAY_BOI_0_0} -quiet] -quiet

# IP: bd/PRG_IDELAY/ip/PRG_IDELAY_IDELAY_CTRL_BOI_0_0/PRG_IDELAY_IDELAY_CTRL_BOI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PRG_IDELAY_IDELAY_CTRL_BOI_0_0 || ORIG_REF_NAME==PRG_IDELAY_IDELAY_CTRL_BOI_0_0} -quiet] -quiet

# IP: bd/PRG_IDELAY/ip/PRG_IDELAY_clk_wiz_0_0/PRG_IDELAY_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PRG_IDELAY_clk_wiz_0_0 || ORIG_REF_NAME==PRG_IDELAY_clk_wiz_0_0} -quiet] -quiet

# IP: bd/PRG_IDELAY/ip/PRG_IDELAY_processing_system7_0_0/PRG_IDELAY_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PRG_IDELAY_processing_system7_0_0 || ORIG_REF_NAME==PRG_IDELAY_processing_system7_0_0} -quiet] -quiet

# IP: bd/PRG_IDELAY/ip/PRG_IDELAY_axi_gpio_0_0/PRG_IDELAY_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PRG_IDELAY_axi_gpio_0_0 || ORIG_REF_NAME==PRG_IDELAY_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PRG_IDELAY/ip/PRG_IDELAY_xbar_0/PRG_IDELAY_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PRG_IDELAY_xbar_0 || ORIG_REF_NAME==PRG_IDELAY_xbar_0} -quiet] -quiet

# IP: bd/PRG_IDELAY/ip/PRG_IDELAY_ps7_0_axi_periph_0/PRG_IDELAY_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PRG_IDELAY_ps7_0_axi_periph_0 || ORIG_REF_NAME==PRG_IDELAY_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PRG_IDELAY/ip/PRG_IDELAY_rst_ps7_0_100M_0/PRG_IDELAY_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PRG_IDELAY_rst_ps7_0_100M_0 || ORIG_REF_NAME==PRG_IDELAY_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/PRG_IDELAY/ip/PRG_IDELAY_xlconstant_0_0/PRG_IDELAY_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PRG_IDELAY_xlconstant_0_0 || ORIG_REF_NAME==PRG_IDELAY_xlconstant_0_0} -quiet] -quiet

# IP: bd/PRG_IDELAY/ip/PRG_IDELAY_del0_0/PRG_IDELAY_del0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PRG_IDELAY_del0_0 || ORIG_REF_NAME==PRG_IDELAY_del0_0} -quiet] -quiet

# IP: bd/PRG_IDELAY/ip/PRG_IDELAY_IDELAY_BOI_0_1/PRG_IDELAY_IDELAY_BOI_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PRG_IDELAY_IDELAY_BOI_0_1 || ORIG_REF_NAME==PRG_IDELAY_IDELAY_BOI_0_1} -quiet] -quiet

# IP: bd/PRG_IDELAY/ip/PRG_IDELAY_util_vector_logic_0_0/PRG_IDELAY_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PRG_IDELAY_util_vector_logic_0_0 || ORIG_REF_NAME==PRG_IDELAY_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/PRG_IDELAY/ip/PRG_IDELAY_auto_pc_0/PRG_IDELAY_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PRG_IDELAY_auto_pc_0 || ORIG_REF_NAME==PRG_IDELAY_auto_pc_0} -quiet] -quiet

# XDC: bd/PRG_IDELAY/ip/PRG_IDELAY_clk_wiz_0_0/PRG_IDELAY_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PRG_IDELAY_clk_wiz_0_0 || ORIG_REF_NAME==PRG_IDELAY_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/PRG_IDELAY/ip/PRG_IDELAY_clk_wiz_0_0/PRG_IDELAY_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PRG_IDELAY_clk_wiz_0_0 || ORIG_REF_NAME==PRG_IDELAY_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/PRG_IDELAY/ip/PRG_IDELAY_clk_wiz_0_0/PRG_IDELAY_clk_wiz_0_0_ooc.xdc

# XDC: bd/PRG_IDELAY/ip/PRG_IDELAY_processing_system7_0_0/PRG_IDELAY_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PRG_IDELAY_processing_system7_0_0 || ORIG_REF_NAME==PRG_IDELAY_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/PRG_IDELAY/ip/PRG_IDELAY_axi_gpio_0_0/PRG_IDELAY_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PRG_IDELAY_axi_gpio_0_0 || ORIG_REF_NAME==PRG_IDELAY_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PRG_IDELAY/ip/PRG_IDELAY_axi_gpio_0_0/PRG_IDELAY_axi_gpio_0_0_ooc.xdc

# XDC: bd/PRG_IDELAY/ip/PRG_IDELAY_axi_gpio_0_0/PRG_IDELAY_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PRG_IDELAY_axi_gpio_0_0 || ORIG_REF_NAME==PRG_IDELAY_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PRG_IDELAY/ip/PRG_IDELAY_rst_ps7_0_100M_0/PRG_IDELAY_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PRG_IDELAY_rst_ps7_0_100M_0 || ORIG_REF_NAME==PRG_IDELAY_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PRG_IDELAY/ip/PRG_IDELAY_rst_ps7_0_100M_0/PRG_IDELAY_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PRG_IDELAY_rst_ps7_0_100M_0 || ORIG_REF_NAME==PRG_IDELAY_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PRG_IDELAY/ip/PRG_IDELAY_del0_0/PRG_IDELAY_del0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PRG_IDELAY_del0_0 || ORIG_REF_NAME==PRG_IDELAY_del0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PRG_IDELAY/ip/PRG_IDELAY_del0_0/PRG_IDELAY_del0_0_ooc.xdc

# XDC: bd/PRG_IDELAY/ip/PRG_IDELAY_del0_0/PRG_IDELAY_del0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PRG_IDELAY_del0_0 || ORIG_REF_NAME==PRG_IDELAY_del0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PRG_IDELAY/ip/PRG_IDELAY_auto_pc_0/PRG_IDELAY_auto_pc_0_ooc.xdc

# XDC: bd/PRG_IDELAY/PRG_IDELAY_ooc.xdc
