# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ-Z1.xdc

# Block Designs: bd/DDR_SCH_TEST/DDR_SCH_TEST.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST || ORIG_REF_NAME==DDR_SCH_TEST} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_DDR_EDGE_DETECT_wrap_0_0/DDR_SCH_TEST_DDR_EDGE_DETECT_wrap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_DDR_EDGE_DETECT_wrap_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_DDR_EDGE_DETECT_wrap_0_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_DDR_EDGE_DETECT_wrap_0_0/src/ddr_edge_ctr/ddr_edge_ctr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_edge_ctr || ORIG_REF_NAME==ddr_edge_ctr} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_processing_system7_0_0/DDR_SCH_TEST_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_processing_system7_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_processing_system7_0_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_axi_gpio_0_0/DDR_SCH_TEST_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_axi_gpio_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_xlconcat_0_0/DDR_SCH_TEST_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_xlconcat_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_xlconcat_0_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_xbar_0/DDR_SCH_TEST_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_xbar_0 || ORIG_REF_NAME==DDR_SCH_TEST_xbar_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_ps7_0_axi_periph_0/DDR_SCH_TEST_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_ps7_0_axi_periph_0 || ORIG_REF_NAME==DDR_SCH_TEST_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_rst_ps7_0_100M_0/DDR_SCH_TEST_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_rst_ps7_0_100M_0 || ORIG_REF_NAME==DDR_SCH_TEST_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_IODELAY_BLK_wrapper_0_0/DDR_SCH_TEST_IODELAY_BLK_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_IODELAY_BLK_wrapper_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_IODELAY_BLK_wrapper_0_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_xlconstant_0_0/DDR_SCH_TEST_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_xlconstant_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_xlconstant_0_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_xlconstant_0_1/DDR_SCH_TEST_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_xlconstant_0_1 || ORIG_REF_NAME==DDR_SCH_TEST_xlconstant_0_1} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_clk_wiz_0_0/DDR_SCH_TEST_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_clk_wiz_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_clk_wiz_0_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_clk_wiz_0_1/DDR_SCH_TEST_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_clk_wiz_0_1 || ORIG_REF_NAME==DDR_SCH_TEST_clk_wiz_0_1} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_xlconstant_2_0/DDR_SCH_TEST_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_xlconstant_2_0 || ORIG_REF_NAME==DDR_SCH_TEST_xlconstant_2_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_axi_gpio_1_0/DDR_SCH_TEST_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_axi_gpio_1_0 || ORIG_REF_NAME==DDR_SCH_TEST_axi_gpio_1_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_util_idelay_ctrl_0_0/DDR_SCH_TEST_util_idelay_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_util_idelay_ctrl_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_util_idelay_ctrl_0_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_util_vector_logic_0_0/DDR_SCH_TEST_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_util_vector_logic_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_auto_pc_0/DDR_SCH_TEST_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_auto_pc_0 || ORIG_REF_NAME==DDR_SCH_TEST_auto_pc_0} -quiet] -quiet

# IP: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_DDR_WRAPPER_0_0/DDR_SCH_TEST_DDR_WRAPPER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_DDR_WRAPPER_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_DDR_WRAPPER_0_0} -quiet] -quiet

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_DDR_EDGE_DETECT_wrap_0_0/src/DDR_EDGE_DETECT_ooc.xdc

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_processing_system7_0_0/DDR_SCH_TEST_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_processing_system7_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_axi_gpio_0_0/DDR_SCH_TEST_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_axi_gpio_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_axi_gpio_0_0/DDR_SCH_TEST_axi_gpio_0_0_ooc.xdc

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_axi_gpio_0_0/DDR_SCH_TEST_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_axi_gpio_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_rst_ps7_0_100M_0/DDR_SCH_TEST_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_rst_ps7_0_100M_0 || ORIG_REF_NAME==DDR_SCH_TEST_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_rst_ps7_0_100M_0/DDR_SCH_TEST_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_rst_ps7_0_100M_0 || ORIG_REF_NAME==DDR_SCH_TEST_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_IODELAY_BLK_wrapper_0_0/src/IODELAY_BLK_ooc.xdc

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_clk_wiz_0_0/DDR_SCH_TEST_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_clk_wiz_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_clk_wiz_0_0/DDR_SCH_TEST_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_clk_wiz_0_0 || ORIG_REF_NAME==DDR_SCH_TEST_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_clk_wiz_0_0/DDR_SCH_TEST_clk_wiz_0_0_ooc.xdc

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_clk_wiz_0_1/DDR_SCH_TEST_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_clk_wiz_0_1 || ORIG_REF_NAME==DDR_SCH_TEST_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_clk_wiz_0_1/DDR_SCH_TEST_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_clk_wiz_0_1 || ORIG_REF_NAME==DDR_SCH_TEST_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_clk_wiz_0_1/DDR_SCH_TEST_clk_wiz_0_1_ooc.xdc

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_axi_gpio_1_0/DDR_SCH_TEST_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_axi_gpio_1_0 || ORIG_REF_NAME==DDR_SCH_TEST_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_axi_gpio_1_0/DDR_SCH_TEST_axi_gpio_1_0_ooc.xdc

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_axi_gpio_1_0/DDR_SCH_TEST_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_SCH_TEST_axi_gpio_1_0 || ORIG_REF_NAME==DDR_SCH_TEST_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDR_SCH_TEST/ip/DDR_SCH_TEST_auto_pc_0/DDR_SCH_TEST_auto_pc_0_ooc.xdc

# XDC: bd/DDR_SCH_TEST/DDR_SCH_TEST_ooc.xdc
