set_property IOSTANDARD LVCMOS33 [get_ports idata0]
set_property IOSTANDARD LVCMOS33 [get_ports idata1]
set_property PACKAGE_PIN W14 [get_ports idata0]
set_property PACKAGE_PIN Y14 [get_ports idata1]
set_property PULLDOWN true [get_ports idata0]
set_property PULLDOWN true [get_ports idata1]
