# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ-Z1.xdc

# Block Designs: bd/DDR_CT_TEST_OV/DDR_CT_TEST_OV.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV || ORIG_REF_NAME==DDR_CT_TEST_OV} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_processing_system7_0_0/DDR_CT_TEST_OV_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_processing_system7_0_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_processing_system7_0_0} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_axi_gpio_0_0/DDR_CT_TEST_OV_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_axi_gpio_0_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_xbar_0/DDR_CT_TEST_OV_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_xbar_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_xbar_0} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_ps7_0_axi_periph_0/DDR_CT_TEST_OV_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_ps7_0_axi_periph_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_rst_ps7_0_100M_0/DDR_CT_TEST_OV_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_DDR_CT_0_0/DDR_CT_TEST_OV_DDR_CT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_DDR_CT_0_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_DDR_CT_0_0} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_DDR_CT_0_0/src/DDR_CT_CTR/DDR_CT_CTR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_CTR || ORIG_REF_NAME==DDR_CT_CTR} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_xlconcat_0_0/DDR_CT_TEST_OV_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_xlconcat_0_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_xlconcat_0_0} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_clk_wiz_0_0/DDR_CT_TEST_OV_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_clk_wiz_0_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_clk_wiz_0_0} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_axi_gpio_1_0/DDR_CT_TEST_OV_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_axi_gpio_1_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_axi_gpio_1_0} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_DDR_WRAPPER_0_0/DDR_CT_TEST_OV_DDR_WRAPPER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_DDR_WRAPPER_0_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_DDR_WRAPPER_0_0} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_DDR_WRAPPER_0_1/DDR_CT_TEST_OV_DDR_WRAPPER_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_DDR_WRAPPER_0_1 || ORIG_REF_NAME==DDR_CT_TEST_OV_DDR_WRAPPER_0_1} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_META32_0_0/DDR_CT_TEST_OV_META32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_META32_0_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_META32_0_0} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_META4_0_0/DDR_CT_TEST_OV_META4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_META4_0_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_META4_0_0} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_axi_gpio_2_0/DDR_CT_TEST_OV_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_axi_gpio_2_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_axi_gpio_2_0} -quiet] -quiet

# IP: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_auto_pc_0/DDR_CT_TEST_OV_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_auto_pc_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_auto_pc_0} -quiet] -quiet

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_processing_system7_0_0/DDR_CT_TEST_OV_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_processing_system7_0_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_axi_gpio_0_0/DDR_CT_TEST_OV_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_axi_gpio_0_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_axi_gpio_0_0/DDR_CT_TEST_OV_axi_gpio_0_0_ooc.xdc

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_axi_gpio_0_0/DDR_CT_TEST_OV_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_axi_gpio_0_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_rst_ps7_0_100M_0/DDR_CT_TEST_OV_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_rst_ps7_0_100M_0/DDR_CT_TEST_OV_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_clk_wiz_0_0/DDR_CT_TEST_OV_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_clk_wiz_0_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_clk_wiz_0_0/DDR_CT_TEST_OV_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_clk_wiz_0_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_clk_wiz_0_0/DDR_CT_TEST_OV_clk_wiz_0_0_ooc.xdc

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_axi_gpio_1_0/DDR_CT_TEST_OV_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_axi_gpio_1_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_axi_gpio_1_0/DDR_CT_TEST_OV_axi_gpio_1_0_ooc.xdc

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_axi_gpio_1_0/DDR_CT_TEST_OV_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_axi_gpio_1_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_axi_gpio_2_0/DDR_CT_TEST_OV_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_axi_gpio_2_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_axi_gpio_2_0/DDR_CT_TEST_OV_axi_gpio_2_0_ooc.xdc

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_axi_gpio_2_0/DDR_CT_TEST_OV_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_CT_TEST_OV_axi_gpio_2_0 || ORIG_REF_NAME==DDR_CT_TEST_OV_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DDR_CT_TEST_OV/ip/DDR_CT_TEST_OV_auto_pc_0/DDR_CT_TEST_OV_auto_pc_0_ooc.xdc

# XDC: bd/DDR_CT_TEST_OV/DDR_CT_TEST_OV_ooc.xdc
