# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/CT_TIMER/CT_TIMER.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CT_TIMER || ORIG_REF_NAME==CT_TIMER} -quiet] -quiet
