create_clock -period 2.500 -waveform {0.000 1.250} [get_nets Counter_Overlay_i/clk_wiz_1_clk_out1]
set_property PACKAGE_PIN W14 [get_ports {INPUT_PULSES[0]}]
set_property PACKAGE_PIN Y14 [get_ports {INPUT_PULSES[1]}]
set_property PACKAGE_PIN T11 [get_ports {INPUT_PULSES[2]}]
set_property PACKAGE_PIN T10 [get_ports {INPUT_PULSES[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {INPUT_PULSES[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {INPUT_PULSES[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {INPUT_PULSES[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {INPUT_PULSES[0]}]
set_property PULLDOWN true [get_ports {INPUT_PULSES}]
