#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : SDDR_CT_AXI.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Feb 03 11:06:13 +1300 2020
# SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: SDDR_CT_AXI.sh [-help]
# usage: SDDR_CT_AXI.sh [-lib_map_path]
# usage: SDDR_CT_AXI.sh [-noclean_files]
# usage: SDDR_CT_AXI.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'SDDR_CT_AXI.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm xbip_utils_v3_0_10 c_reg_fd_v12_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_13 c_gate_bit_v12_0_6 xbip_counter_v3_0_6 c_counter_binary_v12_0_13 axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_21 fifo_generator_v13_2_4 xlconcat_v2_1_3 util_vector_logic_v2_0_1 xlslice_v1_0_2)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "SDDR_CT_AXI.sh - Script generated by export_simulation (Vivado v2019.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_SDDR_CT_0_0/src/CT_TIMER/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_SDDR_CT_0_0/src/CT_TIMER/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_SDDR_CT_0_0/src/CT_TIMER/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_SDDR_CT_0_0/src/CT_TIMER/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_SDDR_CT_0_0/src/CT_TIMER/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_SDDR_CT_0_0/src/CT_TIMER/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_13 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_SDDR_CT_0_0/src/CT_TIMER/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_SDDR_CT_0_0/src/CT_TIMER/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_SDDR_CT_0_0/src/CT_TIMER/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_13 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_SDDR_CT_0_0/src/CT_TIMER/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_SDDR_CT_0_0/src/CT_TIMER/sim/CT_TIMER.vhd" \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ipshared/c9c6/src/SDDR_CT.vhd" \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ipshared/c9c6/src/ISERDES_WRAPPER.vhd" \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_SDDR_CT_0_0/sim/SDDR_CT_AXI_SDDR_CT_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_21 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ipshared/9c6e/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_axi_gpio_0_0/sim/SDDR_CT_AXI_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_axi_gpio_0_1/sim/SDDR_CT_AXI_axi_gpio_0_1.vhd" \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_CTA_SPLIT_0_0/sim/SDDR_CT_AXI_CTA_SPLIT_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ipshared/1f5a/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_4 $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_fifo_generator_0_0/sim/SDDR_CT_AXI_fifo_generator_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_CT_FIFO_R_CT_0_0/sim/SDDR_CT_AXI_CT_FIFO_R_CT_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_xlconcat_0_1/sim/SDDR_CT_AXI_xlconcat_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_util_vector_logic_0_0/sim/SDDR_CT_AXI_util_vector_logic_0_0.v" \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_util_vector_logic_0_1/sim/SDDR_CT_AXI_util_vector_logic_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_ct_capacity_controll_0_0/sim/SDDR_CT_AXI_ct_capacity_controll_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_util_vector_logic_2_0/sim/SDDR_CT_AXI_util_vector_logic_2_0.v" \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_util_vector_logic_3_0/sim/SDDR_CT_AXI_util_vector_logic_3_0.v" \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_xlconcat_1_1/sim/SDDR_CT_AXI_xlconcat_1_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ipshared/f044/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_xlslice_0_0/sim/SDDR_CT_AXI_xlslice_0_0.v" \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/ip/SDDR_CT_AXI_xlslice_0_1/sim/SDDR_CT_AXI_xlslice_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../SDDR_CT_AXI.srcs/sources_1/bd/SDDR_CT_AXI/sim/SDDR_CT_AXI.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.SDDR_CT_AXI xil_defaultlib.glbl -o SDDR_CT_AXI_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./SDDR_CT_AXI_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./SDDR_CT_AXI.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key SDDR_CT_AXI_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc SDDR_CT_AXI_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./SDDR_CT_AXI.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: SDDR_CT_AXI.sh [-help]\n\
Usage: SDDR_CT_AXI.sh [-lib_map_path]\n\
Usage: SDDR_CT_AXI.sh [-reset_run]\n\
Usage: SDDR_CT_AXI.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
