# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ-Z1.xdc

# Block Designs: bd/SP_OV/SP_OV.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV || ORIG_REF_NAME==SP_OV} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_processing_system7_0_0/SP_OV_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_processing_system7_0_0 || ORIG_REF_NAME==SP_OV_processing_system7_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_xbar_0/SP_OV_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_xbar_0 || ORIG_REF_NAME==SP_OV_xbar_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_axi_interconnect_0_0/SP_OV_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_axi_interconnect_0_0 || ORIG_REF_NAME==SP_OV_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_rst_ps7_0_100M_0/SP_OV_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==SP_OV_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_util_vector_logic_0_0/SP_OV_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_util_vector_logic_0_0 || ORIG_REF_NAME==SP_OV_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_util_vector_logic_0_1/SP_OV_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_util_vector_logic_0_1 || ORIG_REF_NAME==SP_OV_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/SP_OV_ST_AXI_PERIPH_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_ST_AXI_PERIPH_wrapper_0_0 || ORIG_REF_NAME==SP_OV_ST_AXI_PERIPH_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_0/ST_AXI_PERIPH_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==ST_AXI_PERIPH_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_1/ST_AXI_PERIPH_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==ST_AXI_PERIPH_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_SCH_IA_wrapper_0_0/ST_AXI_PERIPH_SCH_IA_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ST_AXI_PERIPH_SCH_IA_wrapper_0_0 || ORIG_REF_NAME==ST_AXI_PERIPH_SCH_IA_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_SCH_IA_wrapper_0_0/src/SCH_IA_c_counter_binary_0_0/SCH_IA_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCH_IA_c_counter_binary_0_0 || ORIG_REF_NAME==SCH_IA_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_SCH_IA_wrapper_0_0/src/SCH_IA_util_vector_logic_1_0/SCH_IA_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCH_IA_util_vector_logic_1_0 || ORIG_REF_NAME==SCH_IA_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/SP_OV_P_COUNTER_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_P_COUNTER_wrapper_0_0 || ORIG_REF_NAME==SP_OV_P_COUNTER_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/PC_T_CTR/PC_T_CTR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PC_T_CTR || ORIG_REF_NAME==PC_T_CTR} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data_0/P_COUNTER_axi_gpio_data_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data1_0/P_COUNTER_axi_gpio_data1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data2_0/P_COUNTER_axi_gpio_data2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data3_0/P_COUNTER_axi_gpio_data3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util_0/P_COUNTER_axi_gpio_util_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util1_0/P_COUNTER_axi_gpio_util1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util2_0/P_COUNTER_axi_gpio_util2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util3_0/P_COUNTER_axi_gpio_util3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_c_counter_binary_0_0/P_COUNTER_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_c_counter_binary_0_0 || ORIG_REF_NAME==P_COUNTER_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_c_counter_binary_1_0/P_COUNTER_c_counter_binary_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_c_counter_binary_1_0 || ORIG_REF_NAME==P_COUNTER_c_counter_binary_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_c_counter_binary_2_0/P_COUNTER_c_counter_binary_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_c_counter_binary_2_0 || ORIG_REF_NAME==P_COUNTER_c_counter_binary_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_c_counter_binary_3_0/P_COUNTER_c_counter_binary_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_c_counter_binary_3_0 || ORIG_REF_NAME==P_COUNTER_c_counter_binary_3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_0_0/P_COUNTER_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_0_0 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_1_0/P_COUNTER_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_1_0 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_2_0/P_COUNTER_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_2_0 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_3_0/P_COUNTER_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_3_0 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_4_0/P_COUNTER_util_vector_logic_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_4_0 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_4_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_4_1/P_COUNTER_util_vector_logic_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_4_1 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_4_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_ex_trig_or_1_0/P_COUNTER_ex_trig_or_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_ex_trig_or_1_0 || ORIG_REF_NAME==P_COUNTER_ex_trig_or_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_ex_trig_or_2_0/P_COUNTER_ex_trig_or_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_ex_trig_or_2_0 || ORIG_REF_NAME==P_COUNTER_ex_trig_or_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_util_vector_logic_4_2/P_COUNTER_util_vector_logic_4_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_util_vector_logic_4_2 || ORIG_REF_NAME==P_COUNTER_util_vector_logic_4_2} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_ex_stop_or_0_0/P_COUNTER_ex_stop_or_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_ex_stop_or_0_0 || ORIG_REF_NAME==P_COUNTER_ex_stop_or_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_ex_stop_or_1_0/P_COUNTER_ex_stop_or_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_ex_stop_or_1_0 || ORIG_REF_NAME==P_COUNTER_ex_stop_or_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_ex_stop_or_2_0/P_COUNTER_ex_stop_or_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P_COUNTER_ex_stop_or_2_0 || ORIG_REF_NAME==P_COUNTER_ex_stop_or_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/SP_OV_CT_AXI_PERIPH_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_CT_AXI_PERIPH_wrapper_0_0 || ORIG_REF_NAME==SP_OV_CT_AXI_PERIPH_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/t_counter_0/t_counter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==t_counter_0 || ORIG_REF_NAME==t_counter_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_0/CT_AXI_PERIPH_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CT_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==CT_AXI_PERIPH_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_1/CT_AXI_PERIPH_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CT_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==CT_AXI_PERIPH_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/SP_OV_DDS_AXI_PERIPH_wrapp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_DDS_AXI_PERIPH_wrapp_0_0 || ORIG_REF_NAME==SP_OV_DDS_AXI_PERIPH_wrapp_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_DDS_COM_wrapper_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_DDS_COM_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_DEL_CTR/DDS_DEL_CTR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_DEL_CTR || ORIG_REF_NAME==DDS_DEL_CTR} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_COM_dds_compiler_0_0/DDS_COM_dds_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_dds_compiler_0_0 || ORIG_REF_NAME==DDS_COM_dds_compiler_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_COM_dds_compiler_0_1/DDS_COM_dds_compiler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_dds_compiler_0_1 || ORIG_REF_NAME==DDS_COM_dds_compiler_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_COM_dds_compiler_1_0/DDS_COM_dds_compiler_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_dds_compiler_1_0 || ORIG_REF_NAME==DDS_COM_dds_compiler_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_COM_dds_compiler_2_0/DDS_COM_dds_compiler_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_dds_compiler_2_0 || ORIG_REF_NAME==DDS_COM_dds_compiler_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_COM_xlconcat_0_0/DDS_COM_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_xlconcat_0_0 || ORIG_REF_NAME==DDS_COM_xlconcat_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_COM_xlconcat_0_1/DDS_COM_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_COM_xlconcat_0_1 || ORIG_REF_NAME==DDS_COM_xlconcat_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_0/DDS_AXI_PERIPH_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_0_0/DDS_AXI_PERIPH_phase_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_1_0/DDS_AXI_PERIPH_phase_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_1_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_2_0/DDS_AXI_PERIPH_phase_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_2_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlconcat_0_0/DDS_AXI_PERIPH_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlconcat_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlconcat_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlconcat_0_1/DDS_AXI_PERIPH_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlconcat_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlconcat_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlconcat_1_0/DDS_AXI_PERIPH_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlconcat_1_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlconcat_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlconcat_2_0/DDS_AXI_PERIPH_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlconcat_2_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlconcat_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_1/DDS_AXI_PERIPH_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_0_1/DDS_AXI_PERIPH_aux_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_1_1/DDS_AXI_PERIPH_aux_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_1_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_1_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_2_1/DDS_AXI_PERIPH_aux_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_2_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_2_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_2/DDS_AXI_PERIPH_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_2} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlslice_0_0/DDS_AXI_PERIPH_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlslice_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlslice_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlslice_0_1/DDS_AXI_PERIPH_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlslice_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlslice_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlslice_1_0/DDS_AXI_PERIPH_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlslice_1_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlslice_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlslice_2_0/DDS_AXI_PERIPH_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlslice_2_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlslice_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_xlconcat_4_0/DDS_AXI_PERIPH_xlconcat_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_xlconcat_4_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_xlconcat_4_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_ENABLER_0_0/SP_OV_ENABLER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_ENABLER_0_0 || ORIG_REF_NAME==SP_OV_ENABLER_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_axi_gpio_0_0/SP_OV_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_axi_gpio_0_0 || ORIG_REF_NAME==SP_OV_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_xlslice_0_0/SP_OV_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_xlslice_0_0 || ORIG_REF_NAME==SP_OV_xlslice_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_xlslice_0_1/SP_OV_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_xlslice_0_1 || ORIG_REF_NAME==SP_OV_xlslice_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_axi_gpio_0_1/SP_OV_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_axi_gpio_0_1 || ORIG_REF_NAME==SP_OV_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/SP_OV_TT_AXI_PERIPH_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_TT_AXI_PERIPH_wrapper_0_0 || ORIG_REF_NAME==SP_OV_TT_AXI_PERIPH_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_0/TT_AXI_PERIPH_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_xlconcat_0_0/TT_AXI_PERIPH_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_xlconcat_0_0 || ORIG_REF_NAME==TT_AXI_PERIPH_xlconcat_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_1/TT_AXI_PERIPH_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_xlconcat_1_0/TT_AXI_PERIPH_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_xlconcat_1_0 || ORIG_REF_NAME==TT_AXI_PERIPH_xlconcat_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_2/TT_AXI_PERIPH_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_2} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_xlslice_2_0/TT_AXI_PERIPH_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_xlslice_2_0 || ORIG_REF_NAME==TT_AXI_PERIPH_xlslice_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_xlslice_2_1/TT_AXI_PERIPH_xlslice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_xlslice_2_1 || ORIG_REF_NAME==TT_AXI_PERIPH_xlslice_2_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_LSB_T1_1/TT_AXI_PERIPH_LSB_T1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_LSB_T1_1 || ORIG_REF_NAME==TT_AXI_PERIPH_LSB_T1_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_MSB_T1_1/TT_AXI_PERIPH_MSB_T1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_MSB_T1_1 || ORIG_REF_NAME==TT_AXI_PERIPH_MSB_T1_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_2/TT_AXI_PERIPH_T1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_2 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_2} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_LSB_T1_2/TT_AXI_PERIPH_LSB_T1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_LSB_T1_2 || ORIG_REF_NAME==TT_AXI_PERIPH_LSB_T1_2} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_MSB_T1_2/TT_AXI_PERIPH_MSB_T1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_MSB_T1_2 || ORIG_REF_NAME==TT_AXI_PERIPH_MSB_T1_2} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_3/TT_AXI_PERIPH_T1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_3 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_3} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_LSB_T1_3/TT_AXI_PERIPH_LSB_T1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_LSB_T1_3 || ORIG_REF_NAME==TT_AXI_PERIPH_LSB_T1_3} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_MSB_T1_3/TT_AXI_PERIPH_MSB_T1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_MSB_T1_3 || ORIG_REF_NAME==TT_AXI_PERIPH_MSB_T1_3} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_4/TT_AXI_PERIPH_T1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_4 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_4} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_TIME_TAG_M_0_0/TT_AXI_PERIPH_TIME_TAG_M_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_TIME_TAG_M_0_0 || ORIG_REF_NAME==TT_AXI_PERIPH_TIME_TAG_M_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_TIME_TAG_M_0_0/src/TT_ctr/TT_ctr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TT_ctr || ORIG_REF_NAME==TT_ctr} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_util_vector_logic_2_0/SP_OV_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_util_vector_logic_2_0 || ORIG_REF_NAME==SP_OV_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_util_vector_logic_3_0/SP_OV_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_util_vector_logic_3_0 || ORIG_REF_NAME==SP_OV_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_util_vector_logic_3_1/SP_OV_util_vector_logic_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_util_vector_logic_3_1 || ORIG_REF_NAME==SP_OV_util_vector_logic_3_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_util_vector_logic_3_2/SP_OV_util_vector_logic_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_util_vector_logic_3_2 || ORIG_REF_NAME==SP_OV_util_vector_logic_3_2} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/SP_OV_DD_AXI_PERIPH_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_DD_AXI_PERIPH_wrapper_0_0 || ORIG_REF_NAME==SP_OV_DD_AXI_PERIPH_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_IODELAY_BLK_wrapper_0_0/DD_AXI_PERIPH_IODELAY_BLK_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_IODELAY_BLK_wrapper_0_0 || ORIG_REF_NAME==DD_AXI_PERIPH_IODELAY_BLK_wrapper_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_axi_gpio_0_0/DD_AXI_PERIPH_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==DD_AXI_PERIPH_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_axi_gpio_0_1/DD_AXI_PERIPH_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==DD_AXI_PERIPH_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA_0/DD_AXI_PERIPH_DD_DATA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL_0/DD_AXI_PERIPH_DD_UTIL_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_IODELAY_BLK_wrapper_0_1/DD_AXI_PERIPH_IODELAY_BLK_wrapper_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_IODELAY_BLK_wrapper_0_1 || ORIG_REF_NAME==DD_AXI_PERIPH_IODELAY_BLK_wrapper_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_IODELAY_BLK_wrapper_1_0/DD_AXI_PERIPH_IODELAY_BLK_wrapper_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_IODELAY_BLK_wrapper_1_0 || ORIG_REF_NAME==DD_AXI_PERIPH_IODELAY_BLK_wrapper_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_IODELAY_BLK_wrapper_2_0/DD_AXI_PERIPH_IODELAY_BLK_wrapper_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_IODELAY_BLK_wrapper_2_0 || ORIG_REF_NAME==DD_AXI_PERIPH_IODELAY_BLK_wrapper_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA1_0/DD_AXI_PERIPH_DD_DATA1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA1_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL1_0/DD_AXI_PERIPH_DD_UTIL1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL1_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA2_0/DD_AXI_PERIPH_DD_DATA2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA2_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL2_0/DD_AXI_PERIPH_DD_UTIL2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL2_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_IODELAY_BLK_wrapper_3_0/DD_AXI_PERIPH_IODELAY_BLK_wrapper_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_IODELAY_BLK_wrapper_3_0 || ORIG_REF_NAME==DD_AXI_PERIPH_IODELAY_BLK_wrapper_3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_IODELAY_BLK_wrapper_4_0/DD_AXI_PERIPH_IODELAY_BLK_wrapper_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_IODELAY_BLK_wrapper_4_0 || ORIG_REF_NAME==DD_AXI_PERIPH_IODELAY_BLK_wrapper_4_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA3_0/DD_AXI_PERIPH_DD_DATA3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA3_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL3_0/DD_AXI_PERIPH_DD_UTIL3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL3_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA4_0/DD_AXI_PERIPH_DD_DATA4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA4_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA4_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL4_0/DD_AXI_PERIPH_DD_UTIL4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL4_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL4_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_clk_wiz_0_1/SP_OV_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_0_1 || ORIG_REF_NAME==SP_OV_clk_wiz_0_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_IDELAY_CTRL_WRAPPER_0_0/SP_OV_IDELAY_CTRL_WRAPPER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_IDELAY_CTRL_WRAPPER_0_0 || ORIG_REF_NAME==SP_OV_IDELAY_CTRL_WRAPPER_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_clk_wiz_1_1/SP_OV_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_1_1 || ORIG_REF_NAME==SP_OV_clk_wiz_1_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_clk_wiz_1_2/SP_OV_clk_wiz_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_1_2 || ORIG_REF_NAME==SP_OV_clk_wiz_1_2} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_util_vector_logic_6_0/SP_OV_util_vector_logic_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_util_vector_logic_6_0 || ORIG_REF_NAME==SP_OV_util_vector_logic_6_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_util_vector_logic_7_0/SP_OV_util_vector_logic_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_util_vector_logic_7_0 || ORIG_REF_NAME==SP_OV_util_vector_logic_7_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_xlconcat_0_0/SP_OV_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_xlconcat_0_0 || ORIG_REF_NAME==SP_OV_xlconcat_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_util_vector_logic_6_1/SP_OV_util_vector_logic_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_util_vector_logic_6_1 || ORIG_REF_NAME==SP_OV_util_vector_logic_6_1} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_tier2_xbar_0_0/SP_OV_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_tier2_xbar_0_0 || ORIG_REF_NAME==SP_OV_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_tier2_xbar_1_0/SP_OV_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_tier2_xbar_1_0 || ORIG_REF_NAME==SP_OV_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_tier2_xbar_2_0/SP_OV_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_tier2_xbar_2_0 || ORIG_REF_NAME==SP_OV_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_tier2_xbar_3_0/SP_OV_tier2_xbar_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_tier2_xbar_3_0 || ORIG_REF_NAME==SP_OV_tier2_xbar_3_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_tier2_xbar_4_0/SP_OV_tier2_xbar_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_tier2_xbar_4_0 || ORIG_REF_NAME==SP_OV_tier2_xbar_4_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_tier2_xbar_5_0/SP_OV_tier2_xbar_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_tier2_xbar_5_0 || ORIG_REF_NAME==SP_OV_tier2_xbar_5_0} -quiet] -quiet

# IP: bd/SP_OV/ip/SP_OV_auto_pc_0/SP_OV_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_OV_auto_pc_0 || ORIG_REF_NAME==SP_OV_auto_pc_0} -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_processing_system7_0_0/SP_OV_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_processing_system7_0_0 || ORIG_REF_NAME==SP_OV_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_rst_ps7_0_100M_0/SP_OV_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==SP_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_rst_ps7_0_100M_0/SP_OV_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_rst_ps7_0_100M_0 || ORIG_REF_NAME==SP_OV_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_0/ST_AXI_PERIPH_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==ST_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_0/ST_AXI_PERIPH_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_0/ST_AXI_PERIPH_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==ST_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_1/ST_AXI_PERIPH_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==ST_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_1/ST_AXI_PERIPH_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_axi_gpio_0_1/ST_AXI_PERIPH_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ST_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==ST_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_ST_AXI_PERIPH_wrapper_0_0/src/ST_AXI_PERIPH_SCH_IA_wrapper_0_0/src/SCH_IA_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data_0/P_COUNTER_axi_gpio_data_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data_0/P_COUNTER_axi_gpio_data_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data_0/P_COUNTER_axi_gpio_data_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data1_0/P_COUNTER_axi_gpio_data1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data1_0/P_COUNTER_axi_gpio_data1_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data1_0/P_COUNTER_axi_gpio_data1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data2_0/P_COUNTER_axi_gpio_data2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data2_0/P_COUNTER_axi_gpio_data2_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data2_0/P_COUNTER_axi_gpio_data2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data3_0/P_COUNTER_axi_gpio_data3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data3_0/P_COUNTER_axi_gpio_data3_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_data3_0/P_COUNTER_axi_gpio_data3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_data3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_data3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util_0/P_COUNTER_axi_gpio_util_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util_0/P_COUNTER_axi_gpio_util_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util_0/P_COUNTER_axi_gpio_util_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util1_0/P_COUNTER_axi_gpio_util1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util1_0/P_COUNTER_axi_gpio_util1_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util1_0/P_COUNTER_axi_gpio_util1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util1_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util2_0/P_COUNTER_axi_gpio_util2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util2_0/P_COUNTER_axi_gpio_util2_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util2_0/P_COUNTER_axi_gpio_util2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util2_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util3_0/P_COUNTER_axi_gpio_util3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util3_0/P_COUNTER_axi_gpio_util3_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_P_COUNTER_wrapper_0_0/src/P_COUNTER_axi_gpio_util3_0/P_COUNTER_axi_gpio_util3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==P_COUNTER_axi_gpio_util3_0 || ORIG_REF_NAME==P_COUNTER_axi_gpio_util3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_0/CT_AXI_PERIPH_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CT_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==CT_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_0/CT_AXI_PERIPH_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_0/CT_AXI_PERIPH_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CT_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==CT_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_1/CT_AXI_PERIPH_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CT_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==CT_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_1/CT_AXI_PERIPH_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_CT_AXI_PERIPH_wrapper_0_0/src/CT_AXI_PERIPH_axi_gpio_0_1/CT_AXI_PERIPH_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CT_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==CT_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_DDS_COM_wrapper_0_0/src/DDS_COM_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_0/DDS_AXI_PERIPH_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_0/DDS_AXI_PERIPH_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_0/DDS_AXI_PERIPH_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_0_0/DDS_AXI_PERIPH_phase_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_0_0/DDS_AXI_PERIPH_phase_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_0_0/DDS_AXI_PERIPH_phase_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_0_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_1_0/DDS_AXI_PERIPH_phase_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_1_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_1_0/DDS_AXI_PERIPH_phase_1_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_1_0/DDS_AXI_PERIPH_phase_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_1_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_2_0/DDS_AXI_PERIPH_phase_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_2_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_2_0/DDS_AXI_PERIPH_phase_2_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_phase_2_0/DDS_AXI_PERIPH_phase_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_phase_2_0 || ORIG_REF_NAME==DDS_AXI_PERIPH_phase_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_1/DDS_AXI_PERIPH_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_1/DDS_AXI_PERIPH_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_1/DDS_AXI_PERIPH_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_0_1/DDS_AXI_PERIPH_aux_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_0_1/DDS_AXI_PERIPH_aux_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_0_1/DDS_AXI_PERIPH_aux_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_0_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_1_1/DDS_AXI_PERIPH_aux_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_1_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_1_1/DDS_AXI_PERIPH_aux_1_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_1_1/DDS_AXI_PERIPH_aux_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_1_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_2_1/DDS_AXI_PERIPH_aux_2_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_2_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_2_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_2_1/DDS_AXI_PERIPH_aux_2_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_aux_2_1/DDS_AXI_PERIPH_aux_2_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_aux_2_1 || ORIG_REF_NAME==DDS_AXI_PERIPH_aux_2_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_2/DDS_AXI_PERIPH_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_2/DDS_AXI_PERIPH_axi_gpio_0_2_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DDS_AXI_PERIPH_wrapp_0_0/src/DDS_AXI_PERIPH_axi_gpio_0_2/DDS_AXI_PERIPH_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==DDS_AXI_PERIPH_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_axi_gpio_0_0/SP_OV_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_axi_gpio_0_0 || ORIG_REF_NAME==SP_OV_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_axi_gpio_0_0/SP_OV_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_axi_gpio_0_0/SP_OV_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_axi_gpio_0_0 || ORIG_REF_NAME==SP_OV_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_axi_gpio_0_1/SP_OV_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_axi_gpio_0_1 || ORIG_REF_NAME==SP_OV_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_axi_gpio_0_1/SP_OV_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_axi_gpio_0_1/SP_OV_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_axi_gpio_0_1 || ORIG_REF_NAME==SP_OV_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_0/TT_AXI_PERIPH_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_0/TT_AXI_PERIPH_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_0/TT_AXI_PERIPH_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_1/TT_AXI_PERIPH_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_1/TT_AXI_PERIPH_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_1/TT_AXI_PERIPH_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_2/TT_AXI_PERIPH_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_2/TT_AXI_PERIPH_axi_gpio_0_2_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_axi_gpio_0_2/TT_AXI_PERIPH_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_axi_gpio_0_2 || ORIG_REF_NAME==TT_AXI_PERIPH_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_2/TT_AXI_PERIPH_T1_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_2 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_2/TT_AXI_PERIPH_T1_2_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_2/TT_AXI_PERIPH_T1_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_2 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_3/TT_AXI_PERIPH_T1_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_3 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_3/TT_AXI_PERIPH_T1_3_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_3/TT_AXI_PERIPH_T1_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_3 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_4/TT_AXI_PERIPH_T1_4_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_4 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_4/TT_AXI_PERIPH_T1_4_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_TT_AXI_PERIPH_wrapper_0_0/src/TT_AXI_PERIPH_T1_4/TT_AXI_PERIPH_T1_4.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TT_AXI_PERIPH_T1_4 || ORIG_REF_NAME==TT_AXI_PERIPH_T1_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_IODELAY_BLK_wrapper_0_0/src/IODELAY_BLK_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_axi_gpio_0_0/DD_AXI_PERIPH_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==DD_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_axi_gpio_0_0/DD_AXI_PERIPH_axi_gpio_0_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_axi_gpio_0_0/DD_AXI_PERIPH_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==DD_AXI_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_axi_gpio_0_1/DD_AXI_PERIPH_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==DD_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_axi_gpio_0_1/DD_AXI_PERIPH_axi_gpio_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_axi_gpio_0_1/DD_AXI_PERIPH_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_axi_gpio_0_1 || ORIG_REF_NAME==DD_AXI_PERIPH_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA_0/DD_AXI_PERIPH_DD_DATA_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA_0/DD_AXI_PERIPH_DD_DATA_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA_0/DD_AXI_PERIPH_DD_DATA_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL_0/DD_AXI_PERIPH_DD_UTIL_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL_0/DD_AXI_PERIPH_DD_UTIL_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL_0/DD_AXI_PERIPH_DD_UTIL_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_IODELAY_BLK_wrapper_0_1/src/IODELAY_BLK_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_IODELAY_BLK_wrapper_1_0/src/IODELAY_BLK_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_IODELAY_BLK_wrapper_2_0/src/IODELAY_BLK_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA1_0/DD_AXI_PERIPH_DD_DATA1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA1_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA1_0/DD_AXI_PERIPH_DD_DATA1_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA1_0/DD_AXI_PERIPH_DD_DATA1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA1_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL1_0/DD_AXI_PERIPH_DD_UTIL1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL1_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL1_0/DD_AXI_PERIPH_DD_UTIL1_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL1_0/DD_AXI_PERIPH_DD_UTIL1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL1_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA2_0/DD_AXI_PERIPH_DD_DATA2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA2_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA2_0/DD_AXI_PERIPH_DD_DATA2_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA2_0/DD_AXI_PERIPH_DD_DATA2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA2_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL2_0/DD_AXI_PERIPH_DD_UTIL2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL2_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL2_0/DD_AXI_PERIPH_DD_UTIL2_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL2_0/DD_AXI_PERIPH_DD_UTIL2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL2_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_IODELAY_BLK_wrapper_3_0/src/IODELAY_BLK_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_IODELAY_BLK_wrapper_4_0/src/IODELAY_BLK_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA3_0/DD_AXI_PERIPH_DD_DATA3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA3_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA3_0/DD_AXI_PERIPH_DD_DATA3_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA3_0/DD_AXI_PERIPH_DD_DATA3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA3_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL3_0/DD_AXI_PERIPH_DD_UTIL3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL3_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL3_0/DD_AXI_PERIPH_DD_UTIL3_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL3_0/DD_AXI_PERIPH_DD_UTIL3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL3_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA4_0/DD_AXI_PERIPH_DD_DATA4_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA4_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA4_0/DD_AXI_PERIPH_DD_DATA4_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_DATA4_0/DD_AXI_PERIPH_DD_DATA4_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_DATA4_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_DATA4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL4_0/DD_AXI_PERIPH_DD_UTIL4_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL4_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL4_0/DD_AXI_PERIPH_DD_UTIL4_0_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_DD_AXI_PERIPH_wrapper_0_0/src/DD_AXI_PERIPH_DD_UTIL4_0/DD_AXI_PERIPH_DD_UTIL4_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DD_AXI_PERIPH_DD_UTIL4_0 || ORIG_REF_NAME==DD_AXI_PERIPH_DD_UTIL4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_0_1/SP_OV_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_0_1 || ORIG_REF_NAME==SP_OV_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_0_1/SP_OV_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_0_1 || ORIG_REF_NAME==SP_OV_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_0_1/SP_OV_clk_wiz_0_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_1_1/SP_OV_clk_wiz_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_1_1 || ORIG_REF_NAME==SP_OV_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_1_1/SP_OV_clk_wiz_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_1_1 || ORIG_REF_NAME==SP_OV_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_1_1/SP_OV_clk_wiz_1_1_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_1_2/SP_OV_clk_wiz_1_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_1_2 || ORIG_REF_NAME==SP_OV_clk_wiz_1_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_1_2/SP_OV_clk_wiz_1_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SP_OV_clk_wiz_1_2 || ORIG_REF_NAME==SP_OV_clk_wiz_1_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SP_OV/ip/SP_OV_clk_wiz_1_2/SP_OV_clk_wiz_1_2_ooc.xdc

# XDC: bd/SP_OV/ip/SP_OV_auto_pc_0/SP_OV_auto_pc_0_ooc.xdc

# XDC: bd/SP_OV/SP_OV_ooc.xdc
